import { Shirt, Snowflake, Waves, type LucideIcon } from "lucide-react";

export type Category = {
  id: string;
  label: string;
  icon: LucideIcon;
  image: string;
};

export const categories: Category[] = [
  { id: "camisetas", label: "Camisetas", icon: Shirt, image: "/products/camisas/brooklyn.webp" },
  { id: "pantalonetas", label: "Pantalonetas", icon: Waves, image: "/products/pantalonetas/navy-basic.webp" },
  { id: "polos", label: "Polos", icon: Shirt, image: "/products/polos/negra.webp" },
  { id: "busos", label: "Busos", icon: Snowflake, image: "/products/busos/negro.webp" },
];

export type Product = {
  id: string;
  name: string;
  category: string;
  price: number;
  originalPrice?: number;
  wholesalePrice?: number;
  wholesaleMinQty?: number;
  image: string;
  backImage?: string;
  sizes: string[];
  colors?: string[];
  rating: number;
  reviewCount: number;
  stock: number;
  store: {
    name: string;
    verified: boolean;
  };
  description: string;
};

const SIZES = ["S", "M", "L", "XL"];
const STORE = { name: "J3SAS", verified: true };

export const products: Product[] = [
  {
    id: "brooklyn",
    name: "Camiseta Brooklyn Limited Edition",
    category: "Camisetas",
    price: 55900,
    originalPrice: 65900,
    wholesalePrice: 50000,
    wholesaleMinQty: 12,
    image: "/products/camisas/brooklyn.webp",
    backImage: "/products/camisas/brooklyn-back.webp",
    sizes: SIZES,
    rating: 4.7,
    reviewCount: 38,
    stock: 108,
    store: STORE,
    description: "Camiseta estampado 'Brooklyn Limited Edition', silueta jersey deportivo.",
  },
  {
    id: "california",
    name: "Camiseta California Street",
    category: "Camisetas",
    price: 49900,
    originalPrice: 59900,
    wholesalePrice: 40000,
    wholesaleMinQty: 12,
    image: "/products/camisas/california.webp",
    backImage: "/products/camisas/california-back.webp",
    sizes: SIZES,
    rating: 4.6,
    reviewCount: 27,
    stock: 107,
    store: STORE,
    description: "Camiseta a rayas con estampado gótico 'California', frente y espalda con diseño 'CA Street'.",
  },
  {
    id: "denim",
    name: "Camiseta Denim Patchwork",
    category: "Camisetas",
    price: 52900,
    originalPrice: 62900,
    wholesalePrice: 45000,
    wholesaleMinQty: 12,
    image: "/products/camisas/denim.webp",
    backImage: "/products/camisas/denim-back.webp",
    sizes: SIZES,
    rating: 4.8,
    reviewCount: 41,
    stock: 131,
    store: STORE,
    description: "Camiseta con estampado full print efecto denim parcheado, look urbano y texturizado.",
  },
  {
    id: "exclusive",
    name: "Camiseta Exclusive Pinstripe",
    category: "Camisetas",
    price: 47900,
    originalPrice: 57900,
    wholesalePrice: 40000,
    wholesaleMinQty: 12,
    image: "/products/camisas/exclusive.webp",
    sizes: SIZES,
    rating: 4.5,
    reviewCount: 19,
    stock: 119,
    store: STORE,
    description: "Camiseta a rayas verde y blanco con logo 'Exclusive' bordado al pecho.",
  },
  {
    id: "dragon",
    name: "Camiseta Dragón Tribal",
    category: "Camisetas",
    price: 49900,
    originalPrice: 59900,
    wholesalePrice: 40000,
    wholesaleMinQty: 12,
    image: "/products/camisas/dragon.webp",
    sizes: SIZES,
    rating: 4.8,
    reviewCount: 63,
    stock: 123,
    store: STORE,
    description: "Camiseta blanca con estampado tribal de dragón y caligrafía china, camuflado sutil de fondo.",
  },
  {
    id: "void",
    name: "Camiseta Void Gothic",
    category: "Camisetas",
    price: 51900,
    originalPrice: 61900,
    wholesalePrice: 45000,
    wholesaleMinQty: 12,
    image: "/products/camisas/void.webp",
    backImage: "/products/camisas/void-back.webp",
    sizes: SIZES,
    rating: 4.7,
    reviewCount: 34,
    stock: 104,
    store: STORE,
    description: "Camiseta degradado negro a gris con tipografía gótica 'Void' y detalle '1995' en la espalda.",
  },
  {
    id: "looney-bugs",
    name: "Camiseta Looney Tunes Bugs",
    category: "Camisetas",
    price: 54900,
    originalPrice: 64900,
    wholesalePrice: 45000,
    wholesaleMinQty: 12,
    image: "/products/camisas/looney-bugs.webp",
    backImage: "/products/camisas/looney-bugs-back.webp",
    sizes: SIZES,
    rating: 4.9,
    reviewCount: 87,
    stock: 167,
    store: STORE,
    description: "Camiseta con logo Looney Tunes al frente y arte urbano de Bugs Bunny en la espalda.",
  },
  {
    id: "coyote",
    name: "Camiseta Looney Tunes Coyote",
    category: "Camisetas",
    price: 54900,
    originalPrice: 64900,
    wholesalePrice: 45000,
    wholesaleMinQty: 12,
    image: "/products/camisas/coyote.webp",
    backImage: "/products/camisas/coyote-back.webp",
    sizes: SIZES,
    rating: 4.8,
    reviewCount: 52,
    stock: 142,
    store: STORE,
    description: "Camiseta beige con estampado del Coyote 'Genius #1' y escena de señales de tránsito.",
  },
  {
    id: "daffy",
    name: "Camiseta Looney Tunes Daffy",
    category: "Camisetas",
    price: 54900,
    originalPrice: 64900,
    wholesalePrice: 45000,
    wholesaleMinQty: 12,
    image: "/products/camisas/daffy.webp",
    backImage: "/products/camisas/daffy-back.webp",
    sizes: SIZES,
    rating: 4.7,
    reviewCount: 45,
    stock: 145,
    store: STORE,
    description: "Camiseta negra 'Wake me up when it's Friday' con Daffy Duck estilo graffiti.",
  },
  {
    id: "mickey-cowboys",
    name: "Camiseta Mickey Cowboys",
    category: "Camisetas",
    price: 56900,
    originalPrice: 66900,
    wholesalePrice: 50000,
    wholesaleMinQty: 12,
    image: "/products/camisas/mickey-cowboys.webp",
    backImage: "/products/camisas/mickey-cowboys-back.webp",
    sizes: SIZES,
    rating: 4.6,
    reviewCount: 29,
    stock: 89,
    store: STORE,
    description: "Camiseta raglán blanca y azul con Mickey Mouse jugador de fútbol americano 'Cowboys'.",
  },
  {
    id: "mickey-wow",
    name: "Camiseta Mickey WOW",
    category: "Camisetas",
    price: 53900,
    originalPrice: 63900,
    wholesalePrice: 45000,
    wholesaleMinQty: 12,
    image: "/products/camisas/mickey-wow.webp",
    backImage: "/products/camisas/mickey-wow-back.webp",
    sizes: SIZES,
    rating: 4.7,
    reviewCount: 33,
    stock: 103,
    store: STORE,
    description: "Camiseta bloques pastel con arte abstracto de Mickey Mouse estilo grafiti 'WOW!'.",
  },
  {
    id: "urbn",
    name: "Camiseta URBN Experience",
    category: "Camisetas",
    price: 48900,
    originalPrice: 58900,
    wholesalePrice: 40000,
    wholesaleMinQty: 12,
    image: "/products/camisas/urbn.webp",
    backImage: "/products/camisas/urbn-back.webp",
    sizes: SIZES,
    rating: 4.6,
    reviewCount: 24,
    stock: 104,
    store: STORE,
    description: "Camiseta degradado naranja 'URBN Experience Northeast Division', diseño tipográfico moderno.",
  },
  {
    id: "samurai",
    name: "Camiseta Samurai Sakura",
    category: "Camisetas",
    price: 52900,
    originalPrice: 62900,
    wholesalePrice: 45000,
    wholesaleMinQty: 12,
    image: "/products/camisas/samurai.webp",
    backImage: "/products/camisas/samurai-back.webp",
    sizes: SIZES,
    rating: 4.9,
    reviewCount: 71,
    stock: 161,
    store: STORE,
    description: "Camiseta blanca con arte japonés de cerezos, templo y caligrafía, acentos morado y rosa.",
  },
  {
    id: "yakuza",
    name: "Camiseta Yakuza Underworld",
    category: "Camisetas",
    price: 57900,
    originalPrice: 67900,
    wholesalePrice: 50000,
    wholesaleMinQty: 12,
    image: "/products/camisas/yakuza.webp",
    backImage: "/products/camisas/yakuza-back.webp",
    sizes: SIZES,
    rating: 4.8,
    reviewCount: 48,
    stock: 148,
    store: STORE,
    description: "Camiseta oversize gris con arte de guerrero y dragón tatuado 'Yakuza Underworld Kings'.",
  },
  {
    id: "eagle-crest",
    name: "Camiseta Eagle Crest",
    category: "Camisetas",
    price: 50900,
    originalPrice: 60900,
    wholesalePrice: 45000,
    wholesaleMinQty: 12,
    image: "/products/camisas/eagle-crest.webp",
    sizes: SIZES,
    rating: 4.5,
    reviewCount: 16,
    stock: 76,
    store: STORE,
    description: "Camiseta negro y blanco a rayas con escudo de águila bordado, estilo jersey deportivo.",
  },
  {
    id: "blue-star",
    name: "Camiseta Blue Star",
    category: "Camisetas",
    price: 51900,
    originalPrice: 61900,
    wholesalePrice: 45000,
    wholesaleMinQty: 12,
    image: "/products/camisas/blue-star.webp",
    sizes: SIZES,
    rating: 4.6,
    reviewCount: 22,
    stock: 92,
    store: STORE,
    description: "Camiseta jersey azul cielo con gráfica geométrica de estrella y detalle 'III'.",
  },
  {
    id: "antler-forest",
    name: "Camiseta Antler Forest",
    category: "Camisetas",
    price: 48900,
    originalPrice: 58900,
    wholesalePrice: 40000,
    wholesaleMinQty: 12,
    image: "/products/camisas/antler-forest.webp",
    sizes: SIZES,
    rating: 4.5,
    reviewCount: 14,
    stock: 94,
    store: STORE,
    description: "Camiseta colorblock verde militar y beige con logo de astas minimalista.",
  },
  {
    id: "newspaper-type",
    name: "Camiseta Newspaper Type",
    category: "Camisetas",
    price: 47900,
    originalPrice: 57900,
    wholesalePrice: 40000,
    wholesaleMinQty: 12,
    image: "/products/camisas/newspaper-type.webp",
    sizes: SIZES,
    rating: 4.4,
    reviewCount: 12,
    stock: 102,
    store: STORE,
    description: "Camiseta full print en blanco y negro con collage tipográfico estilo recorte de periódico.",
  },
  {
    id: "la-23",
    name: "Camiseta LA 23",
    category: "Camisetas",
    price: 54900,
    originalPrice: 64900,
    wholesalePrice: 45000,
    wholesaleMinQty: 12,
    image: "/products/camisas/la-23.webp",
    sizes: SIZES,
    rating: 4.7,
    reviewCount: 39,
    stock: 139,
    store: STORE,
    description: "Camiseta jersey negra a rayas 'Los Angeles 23' en rojo, estilo retro deportivo.",
  },
  {
    id: "grunge-type",
    name: "Camiseta Grunge Type",
    category: "Camisetas",
    price: 46900,
    originalPrice: 56900,
    wholesalePrice: 40000,
    wholesaleMinQty: 12,
    image: "/products/camisas/grunge-type.webp",
    sizes: SIZES,
    rating: 4.4,
    reviewCount: 11,
    stock: 71,
    store: STORE,
    description: "Camiseta negra con tipografía grunge desgastada en blanco, estilo urbano abstracto.",
  },
  {
    id: "king-crest",
    name: "Camiseta King Crest",
    category: "Camisetas",
    price: 52900,
    originalPrice: 62900,
    wholesalePrice: 45000,
    wholesaleMinQty: 12,
    image: "/products/camisas/king-crest.webp",
    sizes: SIZES,
    rating: 4.6,
    reviewCount: 25,
    stock: 95,
    store: STORE,
    description: "Camiseta jersey amarilla y negra con escudo 'King' y mangas raglán a rayas.",
  },
  {
    id: "flames",
    name: "Camiseta Flames",
    category: "Camisetas",
    price: 49900,
    originalPrice: 59900,
    wholesalePrice: 40000,
    wholesaleMinQty: 12,
    image: "/products/camisas/flames.webp",
    sizes: SIZES,
    rating: 4.8,
    reviewCount: 56,
    stock: 136,
    store: STORE,
    description: "Camiseta blanca con llamas tribales en blanco y negro que envuelven mangas y torso.",
  },
  {
    id: "brooklyn-boston",
    name: "Camiseta Brooklyn Boston",
    category: "Camisetas",
    price: 53900,
    originalPrice: 63900,
    wholesalePrice: 45000,
    wholesaleMinQty: 12,
    image: "/products/camisas/brooklyn-boston.webp",
    sizes: SIZES,
    rating: 4.5,
    reviewCount: 18,
    stock: 108,
    store: STORE,
    description: "Camiseta roja jersey número 10 con degradado 'Brooklyn Boston', doble estampado en mangas.",
  },
  {
    id: "cool-cats",
    name: "Camiseta Cool Cats",
    category: "Camisetas",
    price: 47900,
    originalPrice: 57900,
    wholesalePrice: 40000,
    wholesaleMinQty: 12,
    image: "/products/camisas/cool-cats.webp",
    sizes: SIZES,
    rating: 4.4,
    reviewCount: 9,
    stock: 109,
    store: STORE,
    description: "Camiseta full print grunge 'Born to Break Silence' con mascota gato estilo urbano.",
  },
  {
    id: "old-school-bugs",
    name: "Camiseta Old School Bugs",
    category: "Camisetas",
    price: 55900,
    originalPrice: 65900,
    wholesalePrice: 50000,
    wholesaleMinQty: 12,
    image: "/products/camisas/old-school-bugs.webp",
    sizes: SIZES,
    rating: 4.6,
    reviewCount: 21,
    stock: 81,
    store: STORE,
    description: "Camiseta negra collage de parches vintage con Bugs Bunny y frases 'Old School'.",
  },
  {
    id: "orelsan-chicago",
    name: "Camiseta Chicago Verde",
    category: "Camisetas",
    price: 51900,
    originalPrice: 61900,
    wholesalePrice: 45000,
    wholesaleMinQty: 12,
    image: "/products/camisas/orelsan-chicago.webp",
    sizes: SIZES,
    rating: 4.5,
    reviewCount: 15,
    stock: 85,
    store: STORE,
    description: "Camiseta jersey verde y negro estilo streetwear con mascota y detalles dorados 'Chicago'.",
  },
  {
    id: "street-mode",
    name: "Camiseta Street Mode",
    category: "Camisetas",
    price: 48900,
    originalPrice: 58900,
    wholesalePrice: 40000,
    wholesaleMinQty: 12,
    image: "/products/camisas/street-mode.webp",
    sizes: SIZES,
    rating: 4.6,
    reviewCount: 20,
    stock: 100,
    store: STORE,
    description: "Camiseta bicolor azul marino y blanco con rayas onduladas y logo 'Street Mode'.",
  },
  {
    id: "brooklyn-93",
    name: "Camiseta Brooklyn 93",
    category: "Camisetas",
    price: 52900,
    originalPrice: 62900,
    wholesalePrice: 45000,
    wholesaleMinQty: 12,
    image: "/products/camisas/brooklyn-93.webp",
    sizes: SIZES,
    rating: 4.7,
    reviewCount: 31,
    stock: 121,
    store: STORE,
    description: "Camiseta negro y blanco 'Brooklyn 93' con flamas y estrellas en las mangas.",
  },
  {
    id: "boston-30",
    name: "Camiseta Boston 30",
    category: "Camisetas",
    price: 54900,
    originalPrice: 64900,
    wholesalePrice: 45000,
    wholesaleMinQty: 12,
    image: "/products/camisas/boston-30.webp",
    sizes: SIZES,
    rating: 4.6,
    reviewCount: 17,
    stock: 117,
    store: STORE,
    description: "Camiseta tipo jersey de botones blanca y azul 'Boston 30' con escudo bordado.",
  },
  {
    id: "paris-france",
    name: "Camiseta Paris France",
    category: "Camisetas",
    price: 46900,
    originalPrice: 56900,
    wholesalePrice: 40000,
    wholesaleMinQty: 12,
    image: "/products/camisas/paris-france.webp",
    sizes: SIZES,
    rating: 4.5,
    reviewCount: 13,
    stock: 73,
    store: STORE,
    description: "Camiseta minimalista blanco y negro 'Paris France' con franja tricolor.",
  },
  {
    id: "la-dodgers",
    name: "Camiseta LA Denim Logo",
    category: "Camisetas",
    price: 53900,
    originalPrice: 63900,
    wholesalePrice: 45000,
    wholesaleMinQty: 12,
    image: "/products/camisas/la-dodgers.webp",
    sizes: SIZES,
    rating: 4.7,
    reviewCount: 28,
    stock: 98,
    store: STORE,
    description: "Camiseta blanca con logo 'LA' texturizado efecto denim y mangas raglán vaqueras.",
  },
  {
    id: "magic",
    name: "Camiseta Magic",
    category: "Camisetas",
    price: 47900,
    originalPrice: 57900,
    wholesalePrice: 40000,
    wholesaleMinQty: 12,
    image: "/products/camisas/magic.webp",
    sizes: SIZES,
    rating: 4.4,
    reviewCount: 10,
    stock: 90,
    store: STORE,
    description: "Camiseta blanca y verde oscuro con logo retro 'Magic', mangas contrastantes.",
  },
  {
    id: "urban-grunge",
    name: "Camiseta Urban Grunge",
    category: "Camisetas",
    price: 46900,
    originalPrice: 56900,
    wholesalePrice: 40000,
    wholesaleMinQty: 12,
    image: "/products/camisas/urban-grunge.webp",
    sizes: SIZES,
    rating: 4.3,
    reviewCount: 8,
    stock: 98,
    store: STORE,
    description: "Camiseta blanca con textura desgastada y tipografía collage en blanco y negro.",
  },
  {
    id: "brooklyn-passion",
    name: "Camiseta Brooklyn Passion",
    category: "Camisetas",
    price: 52900,
    originalPrice: 62900,
    wholesalePrice: 45000,
    wholesaleMinQty: 12,
    image: "/products/camisas/brooklyn-passion.webp",
    sizes: SIZES,
    rating: 4.6,
    reviewCount: 23,
    stock: 123,
    store: STORE,
    description: "Camiseta jersey blanco y negro 'Brooklyn New York 23 Passion' con estrellas en mangas.",
  },
  {
    id: "bugs-star",
    name: "Camiseta Bugs Bunny Star",
    category: "Camisetas",
    price: 55900,
    originalPrice: 65900,
    wholesalePrice: 50000,
    wholesaleMinQty: 12,
    image: "/products/camisas/bugs-star.webp",
    sizes: SIZES,
    rating: 4.7,
    reviewCount: 26,
    stock: 86,
    store: STORE,
    description: "Camiseta crema jersey con Bugs Bunny corriendo, número '01' y estrella bordada.",
  },
  {
    id: "nyc-athletic",
    name: "Camiseta NYC Athletic",
    category: "Camisetas",
    price: 51900,
    originalPrice: 61900,
    wholesalePrice: 45000,
    wholesaleMinQty: 12,
    image: "/products/camisas/nyc-athletic.webp",
    sizes: SIZES,
    rating: 4.5,
    reviewCount: 19,
    stock: 89,
    store: STORE,
    description: "Camiseta rosa palo 'New York City University Athletic Division' estilo universitario.",
  },
  {
    id: "hh-monogram",
    name: "Camiseta HH Monogram",
    category: "Camisetas",
    price: 49900,
    originalPrice: 59900,
    wholesalePrice: 40000,
    wholesaleMinQty: 12,
    image: "/products/camisas/hh-monogram.webp",
    sizes: SIZES,
    rating: 4.6,
    reviewCount: 20,
    stock: 100,
    store: STORE,
    description: "Camiseta blanca y celeste con franjas verticales y monograma bordado 'HH'.",
  },
  {
    id: "harry-potter",
    name: "Camiseta Harry Potter 07",
    category: "Camisetas",
    price: 56900,
    originalPrice: 66900,
    wholesalePrice: 50000,
    wholesaleMinQty: 12,
    image: "/products/camisas/harry-potter.webp",
    sizes: SIZES,
    rating: 4.9,
    reviewCount: 64,
    stock: 154,
    store: STORE,
    description: "Camiseta celeste con personajes chibi de Harry Potter, escudo de Hogwarts y número '07'.",
  },
  {
    id: "short-flame-skull",
    name: "Pantaloneta Flame Skull",
    category: "Pantalonetas",
    price: 44900,
    originalPrice: 54900,
    wholesalePrice: 35000,
    wholesaleMinQty: 12,
    image: "/products/pantalonetas/flame-skull.webp",
    sizes: SIZES,
    rating: 4.7,
    reviewCount: 22,
    stock: 122,
    store: STORE,
    description: "Pantaloneta blanca con llamas tribales y calavera estampada, bolsillos laterales y cordón ajustable.",
  },
  {
    id: "short-navy-basic",
    name: "Pantaloneta Navy Básica",
    category: "Pantalonetas",
    price: 39900,
    originalPrice: 49900,
    wholesalePrice: 30000,
    wholesaleMinQty: 12,
    image: "/products/pantalonetas/navy-basic.webp",
    sizes: SIZES,
    rating: 4.5,
    reviewCount: 14,
    stock: 74,
    store: STORE,
    description: "Pantaloneta azul marino texturizada, corte deportivo básico, ideal para el día a día.",
  },
  {
    id: "short-friends-dont-lie",
    name: "Pantaloneta Friends Don't Lie",
    category: "Pantalonetas",
    price: 46900,
    originalPrice: 56900,
    wholesalePrice: 40000,
    wholesaleMinQty: 12,
    image: "/products/pantalonetas/friends-dont-lie.webp",
    sizes: SIZES,
    rating: 4.6,
    reviewCount: 18,
    stock: 88,
    store: STORE,
    description: "Pantaloneta negra full print con estampado 'Friends Don't Lie', detalles rojos y blancos.",
  },
  {
    id: "short-uptop-liberty",
    name: "Pantaloneta Uptop Liberty",
    category: "Pantalonetas",
    price: 47900,
    originalPrice: 57900,
    wholesalePrice: 40000,
    wholesaleMinQty: 12,
    image: "/products/pantalonetas/uptop-liberty.webp",
    sizes: SIZES,
    rating: 4.6,
    reviewCount: 16,
    stock: 96,
    store: STORE,
    description: "Pantaloneta negra con ilustración de la Estatua de la Libertad y estampado 'Uptop'.",
  },
  {
    id: "short-bulls-23",
    name: "Pantaloneta Bulls 23",
    category: "Pantalonetas",
    price: 48900,
    originalPrice: 58900,
    wholesalePrice: 40000,
    wholesaleMinQty: 12,
    image: "/products/pantalonetas/bulls-23.webp",
    sizes: SIZES,
    rating: 4.7,
    reviewCount: 29,
    stock: 119,
    store: STORE,
    description: "Pantaloneta camuflada con logo de toro y número '23', estilo baloncesto.",
  },
  {
    id: "short-puerto-rico-pin",
    name: "Pantaloneta Puerto Rico Pinstripe",
    category: "Pantalonetas",
    price: 45900,
    originalPrice: 55900,
    wholesalePrice: 40000,
    wholesaleMinQty: 12,
    image: "/products/pantalonetas/puerto-rico-pin.webp",
    sizes: SIZES,
    rating: 4.6,
    reviewCount: 21,
    stock: 121,
    store: STORE,
    description: "Pantaloneta blanca a rayas 'Puerto Rico' con bandera bordada.",
  },
  {
    id: "short-puerto-rico-scenic",
    name: "Pantaloneta Puerto Rico Escénica",
    category: "Pantalonetas",
    price: 45900,
    originalPrice: 55900,
    wholesalePrice: 40000,
    wholesaleMinQty: 12,
    image: "/products/pantalonetas/puerto-rico-scenic.webp",
    sizes: SIZES,
    rating: 4.5,
    reviewCount: 12,
    stock: 72,
    store: STORE,
    description: "Pantaloneta con paisaje del Viejo San Juan al atardecer y bandera puertorriqueña.",
  },
  {
    id: "short-gold-camo-star",
    name: "Pantaloneta Gold Camo Star",
    category: "Pantalonetas",
    price: 44900,
    originalPrice: 54900,
    wholesalePrice: 35000,
    wholesaleMinQty: 12,
    image: "/products/pantalonetas/gold-camo-star.webp",
    sizes: SIZES,
    rating: 4.4,
    reviewCount: 9,
    stock: 79,
    store: STORE,
    description: "Pantaloneta camuflada dorada y negra con estrella y emblema circular.",
  },
  {
    id: "short-new-york-nh",
    name: "Pantaloneta New York NH",
    category: "Pantalonetas",
    price: 46900,
    originalPrice: 56900,
    wholesalePrice: 40000,
    wholesaleMinQty: 12,
    image: "/products/pantalonetas/new-york-nh.webp",
    sizes: SIZES,
    rating: 4.6,
    reviewCount: 17,
    stock: 97,
    store: STORE,
    description: "Pantaloneta negra estilo baloncesto con script 'New York' y escudo 'NH'.",
  },
  {
    id: "short-wave-navy",
    name: "Pantaloneta Wave Navy",
    category: "Pantalonetas",
    price: 43900,
    originalPrice: 53900,
    wholesalePrice: 35000,
    wholesaleMinQty: 12,
    image: "/products/pantalonetas/wave-navy.webp",
    sizes: SIZES,
    rating: 4.4,
    reviewCount: 10,
    stock: 100,
    store: STORE,
    description: "Pantaloneta con degradado ondulado azul marino, turquesa y blanco.",
  },
  {
    id: "short-wave-teal",
    name: "Pantaloneta Wave Teal",
    category: "Pantalonetas",
    price: 43900,
    originalPrice: 53900,
    wholesalePrice: 35000,
    wholesaleMinQty: 12,
    image: "/products/pantalonetas/wave-teal.webp",
    sizes: SIZES,
    rating: 4.4,
    reviewCount: 11,
    stock: 111,
    store: STORE,
    description: "Pantaloneta con degradado ondulado verde jade y menta.",
  },
  {
    id: "short-tiger-blue",
    name: "Pantaloneta Tiger Blue",
    category: "Pantalonetas",
    price: 46900,
    originalPrice: 56900,
    wholesalePrice: 40000,
    wholesaleMinQty: 12,
    image: "/products/pantalonetas/tiger-blue.webp",
    sizes: SIZES,
    rating: 4.6,
    reviewCount: 15,
    stock: 75,
    store: STORE,
    description: "Pantaloneta azul rey con ilustración tonal de tigre y tipografía 'Tiger'.",
  },
  {
    id: "short-la-23",
    name: "Pantaloneta Los Angeles 23",
    category: "Pantalonetas",
    price: 47900,
    originalPrice: 57900,
    wholesalePrice: 40000,
    wholesaleMinQty: 12,
    image: "/products/pantalonetas/la-23.webp",
    sizes: SIZES,
    rating: 4.7,
    reviewCount: 24,
    stock: 94,
    store: STORE,
    description: "Pantaloneta petróleo desgastada 'Los Angeles' con número '23' bordado.",
  },
  {
    id: "short-ny-pinstripe",
    name: "Pantaloneta NY Pinstripe Gótica",
    category: "Pantalonetas",
    price: 46900,
    originalPrice: 56900,
    wholesalePrice: 40000,
    wholesaleMinQty: 12,
    image: "/products/pantalonetas/ny-pinstripe.webp",
    sizes: SIZES,
    rating: 4.5,
    reviewCount: 13,
    stock: 93,
    store: STORE,
    description: "Pantaloneta negra a rayas con monograma gótico 'NY' en ambas piernas.",
  },
  {
    id: "short-negative-grunge",
    name: "Pantaloneta Negative Grunge",
    category: "Pantalonetas",
    price: 44900,
    originalPrice: 54900,
    wholesalePrice: 35000,
    wholesaleMinQty: 12,
    image: "/products/pantalonetas/negative-grunge.webp",
    sizes: SIZES,
    rating: 4.3,
    reviewCount: 7,
    stock: 97,
    store: STORE,
    description: "Pantaloneta blanca con textura grunge desgastada y gráfica 'Negative'.",
  },
  {
    id: "short-ny-monogram-camo",
    name: "Pantaloneta NY Monogram Camo",
    category: "Pantalonetas",
    price: 47900,
    originalPrice: 57900,
    wholesalePrice: 40000,
    wholesaleMinQty: 12,
    image: "/products/pantalonetas/ny-monogram-camo.webp",
    sizes: SIZES,
    rating: 4.6,
    reviewCount: 19,
    stock: 119,
    store: STORE,
    description: "Pantaloneta camuflada azul con monograma 'NY' y frase 'Elegance is the product of art'.",
  },
  {
    id: "polo-azul-cielo",
    name: "Polo Azul Cielo",
    category: "Polos",
    price: 44900,
    originalPrice: 52900,
    wholesalePrice: 37000,
    wholesaleMinQty: 12,
    image: "/products/polos/azul-cielo.webp",
    sizes: SIZES,
    rating: 4.3,
    reviewCount: 12,
    stock: 60,
    store: STORE,
    description: "Polo clásica color azul cielo, tela piqué de algodón, silueta regular.",
  },
  {
    id: "polo-azul-oscuro",
    name: "Polo Azul Oscuro",
    category: "Polos",
    price: 45900,
    originalPrice: 53900,
    wholesalePrice: 38000,
    wholesaleMinQty: 12,
    image: "/products/polos/azul-oscuro.webp",
    sizes: SIZES,
    rating: 4.4,
    reviewCount: 15,
    stock: 64,
    store: STORE,
    description: "Polo clásica color azul oscuro, tela piqué de algodón, silueta regular.",
  },
  {
    id: "polo-azul-rey",
    name: "Polo Azul Rey",
    category: "Polos",
    price: 46900,
    originalPrice: 54900,
    wholesalePrice: 38000,
    wholesaleMinQty: 12,
    image: "/products/polos/azul-rey.webp",
    sizes: SIZES,
    rating: 4.5,
    reviewCount: 18,
    stock: 68,
    store: STORE,
    description: "Polo clásica color azul rey, tela piqué de algodón, silueta regular.",
  },
  {
    id: "polo-azul-turquesa",
    name: "Polo Azul Turquesa",
    category: "Polos",
    price: 47900,
    originalPrice: 55900,
    wholesalePrice: 39000,
    wholesaleMinQty: 12,
    image: "/products/polos/azul-turquesa.webp",
    sizes: SIZES,
    rating: 4.6,
    reviewCount: 21,
    stock: 72,
    store: STORE,
    description: "Polo clásica color azul turquesa, tela piqué de algodón, silueta regular.",
  },
  {
    id: "polo-beige",
    name: "Polo Beige",
    category: "Polos",
    price: 48900,
    originalPrice: 56900,
    wholesalePrice: 40000,
    wholesaleMinQty: 12,
    image: "/products/polos/beige.webp",
    sizes: SIZES,
    rating: 4.7,
    reviewCount: 24,
    stock: 76,
    store: STORE,
    description: "Polo clásica color beige, tela piqué de algodón, silueta regular.",
  },
  {
    id: "polo-blanca",
    name: "Polo Blanca",
    category: "Polos",
    price: 44900,
    originalPrice: 52900,
    wholesalePrice: 37000,
    wholesaleMinQty: 12,
    image: "/products/polos/blanca.webp",
    sizes: SIZES,
    rating: 4.3,
    reviewCount: 27,
    stock: 80,
    store: STORE,
    description: "Polo clásica color blanca, tela piqué de algodón, silueta regular.",
  },
  {
    id: "polo-gris-clara",
    name: "Polo Gris Clara",
    category: "Polos",
    price: 45900,
    originalPrice: 53900,
    wholesalePrice: 38000,
    wholesaleMinQty: 12,
    image: "/products/polos/gris-clara.webp",
    sizes: SIZES,
    rating: 4.4,
    reviewCount: 30,
    stock: 84,
    store: STORE,
    description: "Polo clásica color gris clara, tela piqué de algodón, silueta regular.",
  },
  {
    id: "polo-gris-oscuro",
    name: "Polo Gris Oscuro",
    category: "Polos",
    price: 46900,
    originalPrice: 54900,
    wholesalePrice: 38000,
    wholesaleMinQty: 12,
    image: "/products/polos/gris-oscuro.webp",
    sizes: SIZES,
    rating: 4.5,
    reviewCount: 33,
    stock: 88,
    store: STORE,
    description: "Polo clásica color gris oscuro, tela piqué de algodón, silueta regular.",
  },
  {
    id: "polo-moradito",
    name: "Polo Morado",
    category: "Polos",
    price: 47900,
    originalPrice: 55900,
    wholesalePrice: 39000,
    wholesaleMinQty: 12,
    image: "/products/polos/moradito.webp",
    sizes: SIZES,
    rating: 4.6,
    reviewCount: 36,
    stock: 92,
    store: STORE,
    description: "Polo clásica color morado, tela piqué de algodón, silueta regular.",
  },
  {
    id: "polo-mostaza",
    name: "Polo Mostaza",
    category: "Polos",
    price: 48900,
    originalPrice: 56900,
    wholesalePrice: 40000,
    wholesaleMinQty: 12,
    image: "/products/polos/mostaza.webp",
    sizes: SIZES,
    rating: 4.7,
    reviewCount: 39,
    stock: 96,
    store: STORE,
    description: "Polo clásica color mostaza, tela piqué de algodón, silueta regular.",
  },
  {
    id: "polo-naranja",
    name: "Polo Naranja",
    category: "Polos",
    price: 44900,
    originalPrice: 52900,
    wholesalePrice: 37000,
    wholesaleMinQty: 12,
    image: "/products/polos/naranja.webp",
    sizes: SIZES,
    rating: 4.3,
    reviewCount: 42,
    stock: 100,
    store: STORE,
    description: "Polo clásica color naranja, tela piqué de algodón, silueta regular.",
  },
  {
    id: "polo-negra",
    name: "Polo Negra",
    category: "Polos",
    price: 45900,
    originalPrice: 53900,
    wholesalePrice: 38000,
    wholesaleMinQty: 12,
    image: "/products/polos/negra.webp",
    sizes: SIZES,
    rating: 4.4,
    reviewCount: 45,
    stock: 104,
    store: STORE,
    description: "Polo clásica color negra, tela piqué de algodón, silueta regular.",
  },
  {
    id: "polo-rojo",
    name: "Polo Rojo",
    category: "Polos",
    price: 46900,
    originalPrice: 54900,
    wholesalePrice: 38000,
    wholesaleMinQty: 12,
    image: "/products/polos/rojo.webp",
    sizes: SIZES,
    rating: 4.5,
    reviewCount: 48,
    stock: 108,
    store: STORE,
    description: "Polo clásica color rojo, tela piqué de algodón, silueta regular.",
  },
  {
    id: "polo-rosa",
    name: "Polo Rosa",
    category: "Polos",
    price: 47900,
    originalPrice: 55900,
    wholesalePrice: 39000,
    wholesaleMinQty: 12,
    image: "/products/polos/rosa.webp",
    sizes: SIZES,
    rating: 4.6,
    reviewCount: 51,
    stock: 112,
    store: STORE,
    description: "Polo clásica color rosa, tela piqué de algodón, silueta regular.",
  },
  {
    id: "polo-verde-flux",
    name: "Polo Verde Flúor",
    category: "Polos",
    price: 48900,
    originalPrice: 56900,
    wholesalePrice: 40000,
    wholesaleMinQty: 12,
    image: "/products/polos/verde-flux.webp",
    sizes: SIZES,
    rating: 4.7,
    reviewCount: 54,
    stock: 116,
    store: STORE,
    description: "Polo clásica color verde flúor, tela piqué de algodón, silueta regular.",
  },
  {
    id: "polo-verde-militar",
    name: "Polo Verde Militar",
    category: "Polos",
    price: 44900,
    originalPrice: 52900,
    wholesalePrice: 37000,
    wholesaleMinQty: 12,
    image: "/products/polos/verde-militar.webp",
    sizes: SIZES,
    rating: 4.3,
    reviewCount: 57,
    stock: 120,
    store: STORE,
    description: "Polo clásica color verde militar, tela piqué de algodón, silueta regular.",
  },
  {
    id: "buso-azul-turquesa",
    name: "Buso Azul Turquesa",
    category: "Busos",
    price: 74900,
    originalPrice: 86900,
    wholesalePrice: 60000,
    wholesaleMinQty: 12,
    image: "/products/busos/azul-turquesa.webp",
    sizes: SIZES,
    rating: 4.4,
    reviewCount: 10,
    stock: 45,
    store: STORE,
    description: "Buso con capota color azul turquesa, tela de algodón perchado, bolsillo canguro.",
  },
  {
    id: "buso-azul",
    name: "Buso Azul",
    category: "Busos",
    price: 76400,
    originalPrice: 88400,
    wholesalePrice: 61000,
    wholesaleMinQty: 12,
    image: "/products/busos/azul.webp",
    sizes: SIZES,
    rating: 4.5,
    reviewCount: 13,
    stock: 48,
    store: STORE,
    description: "Buso con capota color azul, tela de algodón perchado, bolsillo canguro.",
  },
  {
    id: "buso-beige",
    name: "Buso Beige",
    category: "Busos",
    price: 77900,
    originalPrice: 89900,
    wholesalePrice: 62000,
    wholesaleMinQty: 12,
    image: "/products/busos/beige.webp",
    sizes: SIZES,
    rating: 4.6,
    reviewCount: 16,
    stock: 51,
    store: STORE,
    description: "Buso con capota color beige, tela de algodón perchado, bolsillo canguro.",
  },
  {
    id: "buso-blanco",
    name: "Buso Blanco",
    category: "Busos",
    price: 79400,
    originalPrice: 91400,
    wholesalePrice: 64000,
    wholesaleMinQty: 12,
    image: "/products/busos/blanco.webp",
    sizes: SIZES,
    rating: 4.7,
    reviewCount: 19,
    stock: 54,
    store: STORE,
    description: "Buso con capota color blanco, tela de algodón perchado, bolsillo canguro.",
  },
  {
    id: "buso-gris",
    name: "Buso Gris",
    category: "Busos",
    price: 80900,
    originalPrice: 92900,
    wholesalePrice: 65000,
    wholesaleMinQty: 12,
    image: "/products/busos/gris.webp",
    sizes: SIZES,
    rating: 4.4,
    reviewCount: 22,
    stock: 57,
    store: STORE,
    description: "Buso con capota color gris, tela de algodón perchado, bolsillo canguro.",
  },
  {
    id: "buso-morado-claro",
    name: "Buso Morado Claro",
    category: "Busos",
    price: 82400,
    originalPrice: 94400,
    wholesalePrice: 66000,
    wholesaleMinQty: 12,
    image: "/products/busos/morado-claro.webp",
    sizes: SIZES,
    rating: 4.5,
    reviewCount: 25,
    stock: 60,
    store: STORE,
    description: "Buso con capota color morado claro, tela de algodón perchado, bolsillo canguro.",
  },
  {
    id: "buso-morado-oscuro",
    name: "Buso Morado Oscuro",
    category: "Busos",
    price: 74900,
    originalPrice: 86900,
    wholesalePrice: 60000,
    wholesaleMinQty: 12,
    image: "/products/busos/morado-oscuro.webp",
    sizes: SIZES,
    rating: 4.6,
    reviewCount: 28,
    stock: 63,
    store: STORE,
    description: "Buso con capota color morado oscuro, tela de algodón perchado, bolsillo canguro.",
  },
  {
    id: "buso-mostaza",
    name: "Buso Mostaza",
    category: "Busos",
    price: 76400,
    originalPrice: 88400,
    wholesalePrice: 61000,
    wholesaleMinQty: 12,
    image: "/products/busos/mostaza.webp",
    sizes: SIZES,
    rating: 4.7,
    reviewCount: 31,
    stock: 66,
    store: STORE,
    description: "Buso con capota color mostaza, tela de algodón perchado, bolsillo canguro.",
  },
  {
    id: "buso-naranja",
    name: "Buso Naranja",
    category: "Busos",
    price: 77900,
    originalPrice: 89900,
    wholesalePrice: 62000,
    wholesaleMinQty: 12,
    image: "/products/busos/naranja.webp",
    sizes: SIZES,
    rating: 4.4,
    reviewCount: 34,
    stock: 69,
    store: STORE,
    description: "Buso con capota color naranja, tela de algodón perchado, bolsillo canguro.",
  },
  {
    id: "buso-negro",
    name: "Buso Negro",
    category: "Busos",
    price: 79400,
    originalPrice: 91400,
    wholesalePrice: 64000,
    wholesaleMinQty: 12,
    image: "/products/busos/negro.webp",
    sizes: SIZES,
    rating: 4.5,
    reviewCount: 37,
    stock: 72,
    store: STORE,
    description: "Buso con capota color negro, tela de algodón perchado, bolsillo canguro.",
  },
  {
    id: "buso-pastel",
    name: "Buso Pastel",
    category: "Busos",
    price: 80900,
    originalPrice: 92900,
    wholesalePrice: 65000,
    wholesaleMinQty: 12,
    image: "/products/busos/pastel.webp",
    sizes: SIZES,
    rating: 4.6,
    reviewCount: 40,
    stock: 75,
    store: STORE,
    description: "Buso con capota color pastel, tela de algodón perchado, bolsillo canguro.",
  },
  {
    id: "buso-rosa-claro",
    name: "Buso Rosa Claro",
    category: "Busos",
    price: 82400,
    originalPrice: 94400,
    wholesalePrice: 66000,
    wholesaleMinQty: 12,
    image: "/products/busos/rosa-claro.webp",
    sizes: SIZES,
    rating: 4.7,
    reviewCount: 43,
    stock: 78,
    store: STORE,
    description: "Buso con capota color rosa claro, tela de algodón perchado, bolsillo canguro.",
  },
  {
    id: "buso-rosa",
    name: "Buso Rosa",
    category: "Busos",
    price: 74900,
    originalPrice: 86900,
    wholesalePrice: 60000,
    wholesaleMinQty: 12,
    image: "/products/busos/rosa.webp",
    sizes: SIZES,
    rating: 4.4,
    reviewCount: 46,
    stock: 81,
    store: STORE,
    description: "Buso con capota color rosa, tela de algodón perchado, bolsillo canguro.",
  },
  {
    id: "buso-verde-militar",
    name: "Buso Verde Militar",
    category: "Busos",
    price: 76400,
    originalPrice: 88400,
    wholesalePrice: 61000,
    wholesaleMinQty: 12,
    image: "/products/busos/verde-militar.webp",
    sizes: SIZES,
    rating: 4.5,
    reviewCount: 49,
    stock: 84,
    store: STORE,
    description: "Buso con capota color verde militar, tela de algodón perchado, bolsillo canguro.",
  },
];

export type CartItem = {
  productId: string;
  qty: number;
  size?: string;
};

export const initialCart: CartItem[] = [
  { productId: "flames", qty: 1, size: "L" },
  { productId: "samurai", qty: 1, size: "M" },
];

export const sampleReview = {
  author: "Camila Rodríguez",
  rating: 5,
  date: "13 oct 2024",
  text: "Excelente calidad, superó mis expectativas. La entrega fue rápida y el producto llegó tal cual las fotos.",
};

export function ratingBreakdown() {
  const weights = [0.62, 0.24, 0.09, 0.03, 0.02];
  return [5, 4, 3, 2, 1].map((star, i) => ({ star, pct: Math.round(weights[i] * 100) }));
}
