import { Flower2, Gem, Shirt, Smile, Snowflake, Waves, type LucideIcon } from "lucide-react";

export type Category = {
  id: string;
  label: string;
  icon: LucideIcon;
  image: string;
};

export const categories: Category[] = [
  { id: "camisetas", label: "Camisetas", icon: Shirt, image: "/products/camisas/coyote-modelo.webp" },
  { id: "pantalonetas", label: "Pantalonetas", icon: Waves, image: "/products/pantalonetas/navy-basic.webp" },
  { id: "polos", label: "Polos", icon: Shirt, image: "/products/polos/negra.webp" },
  { id: "buzos", label: "Buzos", icon: Snowflake, image: "/products/buzos/negro.webp" },
  { id: "ninos", label: "Niños", icon: Smile, image: "/products/ninos/mickey-fisherman.webp" },
  { id: "blusas", label: "Blusas", icon: Flower2, image: "/products/blusas/blusa-rosa-palo.webp" },
  { id: "camisas", label: "Camisas", icon: Gem, image: "/products/camisas-dama/camisa-pedreria-blanca.webp" },
];

export type Audience = "hombre" | "mujer" | "nino" | "nina";

export type Product = {
  id: string;
  name: string;
  category: string;
  audience?: Audience;
  price: number;
  originalPrice?: number;
  wholesalePrice?: number;
  wholesaleMinQty?: number;
  image: string;
  backImage?: string;
  sizes: string[];
  colors?: string[];
  rating: number;
  reviewCount: number;
  stock: number;
  store: {
    name: string;
    verified: boolean;
  };
  description: string;
};

export const AUDIENCE_LABEL: Record<Audience, string> = {
  hombre: "Hombre",
  mujer: "Dama",
  nino: "Niño",
  nina: "Niña",
};

export const CATEGORY_AUDIENCES: Record<string, Audience[]> = {
  Camisetas: ["hombre", "mujer"],
  Buzos: ["hombre", "mujer"],
  Polos: ["hombre", "mujer"],
  Pantalonetas: ["hombre", "mujer"],
  Camisas: ["hombre", "mujer"],
  Blusas: ["hombre", "mujer"],
  Niños: ["nino", "nina"],
};

const SIZES = ["S", "M", "L", "XL"];
const KIDS_SIZES = ["4-5", "6-7", "8-9", "10-11", "12-13"];
const STORE = { name: "J3SAS", verified: true };

export const products: Product[] = [
  {
    id: "brooklyn",
    name: "Camiseta Brooklyn Limited Edition",
    category: "Camisetas",
    audience: "hombre",
    price: 55900,
    originalPrice: 65900,
    wholesalePrice: 50000,
    wholesaleMinQty: 12,
    image: "/products/camisas/brooklyn.webp",
    backImage: "/products/camisas/brooklyn-back.webp",
    sizes: SIZES,
    rating: 4.7,
    reviewCount: 38,
    stock: 108,
    store: STORE,
    description: "Camiseta estampado 'Brooklyn Limited Edition', silueta jersey deportivo.",
  },
  {
    id: "california",
    name: "Camiseta California Street",
    category: "Camisetas",
    audience: "hombre",
    price: 49900,
    originalPrice: 59900,
    wholesalePrice: 40000,
    wholesaleMinQty: 12,
    image: "/products/camisas/california.webp",
    backImage: "/products/camisas/california-back.webp",
    sizes: SIZES,
    rating: 4.6,
    reviewCount: 27,
    stock: 107,
    store: STORE,
    description: "Camiseta a rayas con estampado gótico 'California', frente y espalda con diseño 'CA Street'.",
  },
  {
    id: "denim",
    name: "Camiseta Denim Patchwork",
    category: "Camisetas",
    audience: "hombre",
    price: 52900,
    originalPrice: 62900,
    wholesalePrice: 45000,
    wholesaleMinQty: 12,
    image: "/products/camisas/denim.webp",
    backImage: "/products/camisas/denim-back.webp",
    sizes: SIZES,
    rating: 4.8,
    reviewCount: 41,
    stock: 131,
    store: STORE,
    description: "Camiseta con estampado full print efecto denim parcheado, look urbano y texturizado.",
  },
  {
    id: "exclusive",
    name: "Camiseta Exclusive Pinstripe",
    category: "Camisetas",
    audience: "hombre",
    price: 47900,
    originalPrice: 57900,
    wholesalePrice: 40000,
    wholesaleMinQty: 12,
    image: "/products/camisas/exclusive.webp",
    sizes: SIZES,
    rating: 4.5,
    reviewCount: 19,
    stock: 119,
    store: STORE,
    description: "Camiseta a rayas verde y blanco con logo 'Exclusive' bordado al pecho.",
  },
  {
    id: "dragon",
    name: "Camiseta Dragón Tribal",
    category: "Camisetas",
    audience: "hombre",
    price: 49900,
    originalPrice: 59900,
    wholesalePrice: 40000,
    wholesaleMinQty: 12,
    image: "/products/camisas/dragon.webp",
    sizes: SIZES,
    rating: 4.8,
    reviewCount: 63,
    stock: 123,
    store: STORE,
    description: "Camiseta blanca con estampado tribal de dragón y caligrafía china, camuflado sutil de fondo.",
  },
  {
    id: "void",
    name: "Camiseta Void Gothic",
    category: "Camisetas",
    audience: "hombre",
    price: 51900,
    originalPrice: 61900,
    wholesalePrice: 45000,
    wholesaleMinQty: 12,
    image: "/products/camisas/void.webp",
    backImage: "/products/camisas/void-back.webp",
    sizes: SIZES,
    rating: 4.7,
    reviewCount: 34,
    stock: 104,
    store: STORE,
    description: "Camiseta degradado negro a gris con tipografía gótica 'Void' y detalle '1995' en la espalda.",
  },
  {
    id: "looney-bugs",
    name: "Camiseta Looney Tunes Bugs",
    category: "Camisetas",
    audience: "hombre",
    price: 54900,
    originalPrice: 64900,
    wholesalePrice: 45000,
    wholesaleMinQty: 12,
    image: "/products/camisas/looney-bugs.webp",
    backImage: "/products/camisas/looney-bugs-back.webp",
    sizes: SIZES,
    rating: 4.9,
    reviewCount: 87,
    stock: 167,
    store: STORE,
    description: "Camiseta con logo Looney Tunes al frente y arte urbano de Bugs Bunny en la espalda.",
  },
  {
    id: "coyote",
    name: "Camiseta Looney Tunes Coyote",
    category: "Camisetas",
    audience: "hombre",
    price: 54900,
    originalPrice: 64900,
    wholesalePrice: 45000,
    wholesaleMinQty: 12,
    image: "/products/camisas/coyote.webp",
    backImage: "/products/camisas/coyote-back.webp",
    sizes: SIZES,
    rating: 4.8,
    reviewCount: 52,
    stock: 142,
    store: STORE,
    description: "Camiseta beige con estampado del Coyote 'Genius #1' y escena de señales de tránsito.",
  },
  {
    id: "daffy",
    name: "Camiseta Looney Tunes Daffy",
    category: "Camisetas",
    audience: "hombre",
    price: 54900,
    originalPrice: 64900,
    wholesalePrice: 45000,
    wholesaleMinQty: 12,
    image: "/products/camisas/daffy.webp",
    backImage: "/products/camisas/daffy-back.webp",
    sizes: SIZES,
    rating: 4.7,
    reviewCount: 45,
    stock: 145,
    store: STORE,
    description: "Camiseta negra 'Wake me up when it's Friday' con Daffy Duck estilo graffiti.",
  },
  {
    id: "mickey-cowboys",
    name: "Camiseta Mickey Cowboys",
    category: "Camisetas",
    audience: "hombre",
    price: 56900,
    originalPrice: 66900,
    wholesalePrice: 50000,
    wholesaleMinQty: 12,
    image: "/products/camisas/mickey-cowboys.webp",
    backImage: "/products/camisas/mickey-cowboys-back.webp",
    sizes: SIZES,
    rating: 4.6,
    reviewCount: 29,
    stock: 89,
    store: STORE,
    description: "Camiseta raglán blanca y azul con Mickey Mouse jugador de fútbol americano 'Cowboys'.",
  },
  {
    id: "mickey-wow",
    name: "Camiseta Mickey WOW",
    category: "Camisetas",
    audience: "hombre",
    price: 53900,
    originalPrice: 63900,
    wholesalePrice: 45000,
    wholesaleMinQty: 12,
    image: "/products/camisas/mickey-wow.webp",
    backImage: "/products/camisas/mickey-wow-back.webp",
    sizes: SIZES,
    rating: 4.7,
    reviewCount: 33,
    stock: 103,
    store: STORE,
    description: "Camiseta bloques pastel con arte abstracto de Mickey Mouse estilo grafiti 'WOW!'.",
  },
  {
    id: "urbn",
    name: "Camiseta URBN Experience",
    category: "Camisetas",
    audience: "hombre",
    price: 48900,
    originalPrice: 58900,
    wholesalePrice: 40000,
    wholesaleMinQty: 12,
    image: "/products/camisas/urbn.webp",
    backImage: "/products/camisas/urbn-back.webp",
    sizes: SIZES,
    rating: 4.6,
    reviewCount: 24,
    stock: 104,
    store: STORE,
    description: "Camiseta degradado naranja 'URBN Experience Northeast Division', diseño tipográfico moderno.",
  },
  {
    id: "samurai",
    name: "Camiseta Samurai Sakura",
    category: "Camisetas",
    audience: "hombre",
    price: 52900,
    originalPrice: 62900,
    wholesalePrice: 45000,
    wholesaleMinQty: 12,
    image: "/products/camisas/samurai.webp",
    backImage: "/products/camisas/samurai-back.webp",
    sizes: SIZES,
    rating: 4.9,
    reviewCount: 71,
    stock: 161,
    store: STORE,
    description: "Camiseta blanca con arte japonés de cerezos, templo y caligrafía, acentos morado y rosa.",
  },
  {
    id: "yakuza",
    name: "Camiseta Yakuza Underworld",
    category: "Camisetas",
    audience: "hombre",
    price: 57900,
    originalPrice: 67900,
    wholesalePrice: 50000,
    wholesaleMinQty: 12,
    image: "/products/camisas/yakuza.webp",
    backImage: "/products/camisas/yakuza-back.webp",
    sizes: SIZES,
    rating: 4.8,
    reviewCount: 48,
    stock: 148,
    store: STORE,
    description: "Camiseta oversize gris con arte de guerrero y dragón tatuado 'Yakuza Underworld Kings'.",
  },
  {
    id: "eagle-crest",
    name: "Camiseta Eagle Crest",
    category: "Camisetas",
    audience: "hombre",
    price: 50900,
    originalPrice: 60900,
    wholesalePrice: 45000,
    wholesaleMinQty: 12,
    image: "/products/camisas/eagle-crest.webp",
    sizes: SIZES,
    rating: 4.5,
    reviewCount: 16,
    stock: 76,
    store: STORE,
    description: "Camiseta negro y blanco a rayas con escudo de águila bordado, estilo jersey deportivo.",
  },
  {
    id: "blue-star",
    name: "Camiseta Blue Star",
    category: "Camisetas",
    audience: "hombre",
    price: 51900,
    originalPrice: 61900,
    wholesalePrice: 45000,
    wholesaleMinQty: 12,
    image: "/products/camisas/blue-star.webp",
    sizes: SIZES,
    rating: 4.6,
    reviewCount: 22,
    stock: 92,
    store: STORE,
    description: "Camiseta jersey azul cielo con gráfica geométrica de estrella y detalle 'III'.",
  },
  {
    id: "antler-forest",
    name: "Camiseta Antler Forest",
    category: "Camisetas",
    audience: "hombre",
    price: 48900,
    originalPrice: 58900,
    wholesalePrice: 40000,
    wholesaleMinQty: 12,
    image: "/products/camisas/antler-forest.webp",
    sizes: SIZES,
    rating: 4.5,
    reviewCount: 14,
    stock: 94,
    store: STORE,
    description: "Camiseta colorblock verde militar y beige con logo de astas minimalista.",
  },
  {
    id: "newspaper-type",
    name: "Camiseta Newspaper Type",
    category: "Camisetas",
    audience: "hombre",
    price: 47900,
    originalPrice: 57900,
    wholesalePrice: 40000,
    wholesaleMinQty: 12,
    image: "/products/camisas/newspaper-type.webp",
    sizes: SIZES,
    rating: 4.4,
    reviewCount: 12,
    stock: 102,
    store: STORE,
    description: "Camiseta full print en blanco y negro con collage tipográfico estilo recorte de periódico.",
  },
  {
    id: "la-23",
    name: "Camiseta LA 23",
    category: "Camisetas",
    audience: "hombre",
    price: 54900,
    originalPrice: 64900,
    wholesalePrice: 45000,
    wholesaleMinQty: 12,
    image: "/products/camisas/la-23.webp",
    sizes: SIZES,
    rating: 4.7,
    reviewCount: 39,
    stock: 139,
    store: STORE,
    description: "Camiseta jersey negra a rayas 'Los Angeles 23' en rojo, estilo retro deportivo.",
  },
  {
    id: "grunge-type",
    name: "Camiseta Grunge Type",
    category: "Camisetas",
    audience: "hombre",
    price: 46900,
    originalPrice: 56900,
    wholesalePrice: 40000,
    wholesaleMinQty: 12,
    image: "/products/camisas/grunge-type.webp",
    sizes: SIZES,
    rating: 4.4,
    reviewCount: 11,
    stock: 71,
    store: STORE,
    description: "Camiseta negra con tipografía grunge desgastada en blanco, estilo urbano abstracto.",
  },
  {
    id: "king-crest",
    name: "Camiseta King Crest",
    category: "Camisetas",
    audience: "hombre",
    price: 52900,
    originalPrice: 62900,
    wholesalePrice: 45000,
    wholesaleMinQty: 12,
    image: "/products/camisas/king-crest.webp",
    sizes: SIZES,
    rating: 4.6,
    reviewCount: 25,
    stock: 95,
    store: STORE,
    description: "Camiseta jersey amarilla y negra con escudo 'King' y mangas raglán a rayas.",
  },
  {
    id: "flames",
    name: "Camiseta Flames",
    category: "Camisetas",
    audience: "hombre",
    price: 49900,
    originalPrice: 59900,
    wholesalePrice: 40000,
    wholesaleMinQty: 12,
    image: "/products/camisas/flames.webp",
    sizes: SIZES,
    rating: 4.8,
    reviewCount: 56,
    stock: 136,
    store: STORE,
    description: "Camiseta blanca con llamas tribales en blanco y negro que envuelven mangas y torso.",
  },
  {
    id: "brooklyn-boston",
    name: "Camiseta Brooklyn Boston",
    category: "Camisetas",
    audience: "hombre",
    price: 53900,
    originalPrice: 63900,
    wholesalePrice: 45000,
    wholesaleMinQty: 12,
    image: "/products/camisas/brooklyn-boston.webp",
    sizes: SIZES,
    rating: 4.5,
    reviewCount: 18,
    stock: 108,
    store: STORE,
    description: "Camiseta roja jersey número 10 con degradado 'Brooklyn Boston', doble estampado en mangas.",
  },
  {
    id: "cool-cats",
    name: "Camiseta Cool Cats",
    category: "Camisetas",
    audience: "hombre",
    price: 47900,
    originalPrice: 57900,
    wholesalePrice: 40000,
    wholesaleMinQty: 12,
    image: "/products/camisas/cool-cats.webp",
    sizes: SIZES,
    rating: 4.4,
    reviewCount: 9,
    stock: 109,
    store: STORE,
    description: "Camiseta full print grunge 'Born to Break Silence' con mascota gato estilo urbano.",
  },
  {
    id: "old-school-bugs",
    name: "Camiseta Old School Bugs",
    category: "Camisetas",
    audience: "hombre",
    price: 55900,
    originalPrice: 65900,
    wholesalePrice: 50000,
    wholesaleMinQty: 12,
    image: "/products/camisas/old-school-bugs.webp",
    sizes: SIZES,
    rating: 4.6,
    reviewCount: 21,
    stock: 81,
    store: STORE,
    description: "Camiseta negra collage de parches vintage con Bugs Bunny y frases 'Old School'.",
  },
  {
    id: "orelsan-chicago",
    name: "Camiseta Chicago Verde",
    category: "Camisetas",
    audience: "hombre",
    price: 51900,
    originalPrice: 61900,
    wholesalePrice: 45000,
    wholesaleMinQty: 12,
    image: "/products/camisas/orelsan-chicago.webp",
    sizes: SIZES,
    rating: 4.5,
    reviewCount: 15,
    stock: 85,
    store: STORE,
    description: "Camiseta jersey verde y negro estilo streetwear con mascota y detalles dorados 'Chicago'.",
  },
  {
    id: "street-mode",
    name: "Camiseta Street Mode",
    category: "Camisetas",
    audience: "hombre",
    price: 48900,
    originalPrice: 58900,
    wholesalePrice: 40000,
    wholesaleMinQty: 12,
    image: "/products/camisas/street-mode.webp",
    sizes: SIZES,
    rating: 4.6,
    reviewCount: 20,
    stock: 100,
    store: STORE,
    description: "Camiseta bicolor azul marino y blanco con rayas onduladas y logo 'Street Mode'.",
  },
  {
    id: "brooklyn-93",
    name: "Camiseta Brooklyn 93",
    category: "Camisetas",
    audience: "hombre",
    price: 52900,
    originalPrice: 62900,
    wholesalePrice: 45000,
    wholesaleMinQty: 12,
    image: "/products/camisas/brooklyn-93.webp",
    sizes: SIZES,
    rating: 4.7,
    reviewCount: 31,
    stock: 121,
    store: STORE,
    description: "Camiseta negro y blanco 'Brooklyn 93' con flamas y estrellas en las mangas.",
  },
  {
    id: "boston-30",
    name: "Camiseta Boston 30",
    category: "Camisetas",
    audience: "hombre",
    price: 54900,
    originalPrice: 64900,
    wholesalePrice: 45000,
    wholesaleMinQty: 12,
    image: "/products/camisas/boston-30.webp",
    sizes: SIZES,
    rating: 4.6,
    reviewCount: 17,
    stock: 117,
    store: STORE,
    description: "Camiseta tipo jersey de botones blanca y azul 'Boston 30' con escudo bordado.",
  },
  {
    id: "paris-france",
    name: "Camiseta Paris France",
    category: "Camisetas",
    audience: "hombre",
    price: 46900,
    originalPrice: 56900,
    wholesalePrice: 40000,
    wholesaleMinQty: 12,
    image: "/products/camisas/paris-france.webp",
    sizes: SIZES,
    rating: 4.5,
    reviewCount: 13,
    stock: 73,
    store: STORE,
    description: "Camiseta minimalista blanco y negro 'Paris France' con franja tricolor.",
  },
  {
    id: "la-dodgers",
    name: "Camiseta LA Denim Logo",
    category: "Camisetas",
    audience: "hombre",
    price: 53900,
    originalPrice: 63900,
    wholesalePrice: 45000,
    wholesaleMinQty: 12,
    image: "/products/camisas/la-dodgers.webp",
    sizes: SIZES,
    rating: 4.7,
    reviewCount: 28,
    stock: 98,
    store: STORE,
    description: "Camiseta blanca con logo 'LA' texturizado efecto denim y mangas raglán vaqueras.",
  },
  {
    id: "magic",
    name: "Camiseta Magic",
    category: "Camisetas",
    audience: "hombre",
    price: 47900,
    originalPrice: 57900,
    wholesalePrice: 40000,
    wholesaleMinQty: 12,
    image: "/products/camisas/magic.webp",
    sizes: SIZES,
    rating: 4.4,
    reviewCount: 10,
    stock: 90,
    store: STORE,
    description: "Camiseta blanca y verde oscuro con logo retro 'Magic', mangas contrastantes.",
  },
  {
    id: "urban-grunge",
    name: "Camiseta Urban Grunge",
    category: "Camisetas",
    audience: "hombre",
    price: 46900,
    originalPrice: 56900,
    wholesalePrice: 40000,
    wholesaleMinQty: 12,
    image: "/products/camisas/urban-grunge.webp",
    sizes: SIZES,
    rating: 4.3,
    reviewCount: 8,
    stock: 98,
    store: STORE,
    description: "Camiseta blanca con textura desgastada y tipografía collage en blanco y negro.",
  },
  {
    id: "brooklyn-passion",
    name: "Camiseta Brooklyn Passion",
    category: "Camisetas",
    audience: "hombre",
    price: 52900,
    originalPrice: 62900,
    wholesalePrice: 45000,
    wholesaleMinQty: 12,
    image: "/products/camisas/brooklyn-passion.webp",
    sizes: SIZES,
    rating: 4.6,
    reviewCount: 23,
    stock: 123,
    store: STORE,
    description: "Camiseta jersey blanco y negro 'Brooklyn New York 23 Passion' con estrellas en mangas.",
  },
  {
    id: "bugs-star",
    name: "Camiseta Bugs Bunny Star",
    category: "Camisetas",
    audience: "hombre",
    price: 55900,
    originalPrice: 65900,
    wholesalePrice: 50000,
    wholesaleMinQty: 12,
    image: "/products/camisas/bugs-star.webp",
    sizes: SIZES,
    rating: 4.7,
    reviewCount: 26,
    stock: 86,
    store: STORE,
    description: "Camiseta crema jersey con Bugs Bunny corriendo, número '01' y estrella bordada.",
  },
  {
    id: "nyc-athletic",
    name: "Camiseta NYC Athletic",
    category: "Camisetas",
    audience: "hombre",
    price: 51900,
    originalPrice: 61900,
    wholesalePrice: 45000,
    wholesaleMinQty: 12,
    image: "/products/camisas/nyc-athletic.webp",
    sizes: SIZES,
    rating: 4.5,
    reviewCount: 19,
    stock: 89,
    store: STORE,
    description: "Camiseta rosa palo 'New York City University Athletic Division' estilo universitario.",
  },
  {
    id: "hh-monogram",
    name: "Camiseta HH Monogram",
    category: "Camisetas",
    audience: "hombre",
    price: 49900,
    originalPrice: 59900,
    wholesalePrice: 40000,
    wholesaleMinQty: 12,
    image: "/products/camisas/hh-monogram.webp",
    sizes: SIZES,
    rating: 4.6,
    reviewCount: 20,
    stock: 100,
    store: STORE,
    description: "Camiseta blanca y celeste con franjas verticales y monograma bordado 'HH'.",
  },
  {
    id: "harry-potter",
    name: "Camiseta Harry Potter 07",
    category: "Camisetas",
    audience: "hombre",
    price: 56900,
    originalPrice: 66900,
    wholesalePrice: 50000,
    wholesaleMinQty: 12,
    image: "/products/camisas/harry-potter.webp",
    sizes: SIZES,
    rating: 4.9,
    reviewCount: 64,
    stock: 154,
    store: STORE,
    description: "Camiseta celeste con personajes chibi de Harry Potter, escudo de Hogwarts y número '07'.",
  },
  {
    id: "short-flame-skull",
    name: "Pantaloneta Flame Skull",
    category: "Pantalonetas",
    audience: "hombre",
    price: 44900,
    originalPrice: 54900,
    wholesalePrice: 35000,
    wholesaleMinQty: 12,
    image: "/products/pantalonetas/flame-skull.webp",
    sizes: SIZES,
    rating: 4.7,
    reviewCount: 22,
    stock: 122,
    store: STORE,
    description: "Pantaloneta blanca con llamas tribales y calavera estampada, bolsillos laterales y cordón ajustable.",
  },
  {
    id: "short-navy-basic",
    name: "Pantaloneta Navy Básica",
    category: "Pantalonetas",
    audience: "hombre",
    price: 39900,
    originalPrice: 49900,
    wholesalePrice: 30000,
    wholesaleMinQty: 12,
    image: "/products/pantalonetas/navy-basic.webp",
    sizes: SIZES,
    rating: 4.5,
    reviewCount: 14,
    stock: 74,
    store: STORE,
    description: "Pantaloneta azul marino texturizada, corte deportivo básico, ideal para el día a día.",
  },
  {
    id: "short-friends-dont-lie",
    name: "Pantaloneta Friends Don't Lie",
    category: "Pantalonetas",
    audience: "hombre",
    price: 46900,
    originalPrice: 56900,
    wholesalePrice: 40000,
    wholesaleMinQty: 12,
    image: "/products/pantalonetas/friends-dont-lie.webp",
    sizes: SIZES,
    rating: 4.6,
    reviewCount: 18,
    stock: 88,
    store: STORE,
    description: "Pantaloneta negra full print con estampado 'Friends Don't Lie', detalles rojos y blancos.",
  },
  {
    id: "short-uptop-liberty",
    name: "Pantaloneta Uptop Liberty",
    category: "Pantalonetas",
    audience: "hombre",
    price: 47900,
    originalPrice: 57900,
    wholesalePrice: 40000,
    wholesaleMinQty: 12,
    image: "/products/pantalonetas/uptop-liberty.webp",
    sizes: SIZES,
    rating: 4.6,
    reviewCount: 16,
    stock: 96,
    store: STORE,
    description: "Pantaloneta negra con ilustración de la Estatua de la Libertad y estampado 'Uptop'.",
  },
  {
    id: "short-bulls-23",
    name: "Pantaloneta Bulls 23",
    category: "Pantalonetas",
    audience: "hombre",
    price: 48900,
    originalPrice: 58900,
    wholesalePrice: 40000,
    wholesaleMinQty: 12,
    image: "/products/pantalonetas/bulls-23.webp",
    sizes: SIZES,
    rating: 4.7,
    reviewCount: 29,
    stock: 119,
    store: STORE,
    description: "Pantaloneta camuflada con logo de toro y número '23', estilo baloncesto.",
  },
  {
    id: "short-puerto-rico-pin",
    name: "Pantaloneta Puerto Rico Pinstripe",
    category: "Pantalonetas",
    audience: "hombre",
    price: 45900,
    originalPrice: 55900,
    wholesalePrice: 40000,
    wholesaleMinQty: 12,
    image: "/products/pantalonetas/puerto-rico-pin.webp",
    sizes: SIZES,
    rating: 4.6,
    reviewCount: 21,
    stock: 121,
    store: STORE,
    description: "Pantaloneta blanca a rayas 'Puerto Rico' con bandera bordada.",
  },
  {
    id: "short-puerto-rico-scenic",
    name: "Pantaloneta Puerto Rico Escénica",
    category: "Pantalonetas",
    audience: "hombre",
    price: 45900,
    originalPrice: 55900,
    wholesalePrice: 40000,
    wholesaleMinQty: 12,
    image: "/products/pantalonetas/puerto-rico-scenic.webp",
    sizes: SIZES,
    rating: 4.5,
    reviewCount: 12,
    stock: 72,
    store: STORE,
    description: "Pantaloneta con paisaje del Viejo San Juan al atardecer y bandera puertorriqueña.",
  },
  {
    id: "short-gold-camo-star",
    name: "Pantaloneta Gold Camo Star",
    category: "Pantalonetas",
    audience: "hombre",
    price: 44900,
    originalPrice: 54900,
    wholesalePrice: 35000,
    wholesaleMinQty: 12,
    image: "/products/pantalonetas/gold-camo-star.webp",
    sizes: SIZES,
    rating: 4.4,
    reviewCount: 9,
    stock: 79,
    store: STORE,
    description: "Pantaloneta camuflada dorada y negra con estrella y emblema circular.",
  },
  {
    id: "short-new-york-nh",
    name: "Pantaloneta New York NH",
    category: "Pantalonetas",
    audience: "hombre",
    price: 46900,
    originalPrice: 56900,
    wholesalePrice: 40000,
    wholesaleMinQty: 12,
    image: "/products/pantalonetas/new-york-nh.webp",
    sizes: SIZES,
    rating: 4.6,
    reviewCount: 17,
    stock: 97,
    store: STORE,
    description: "Pantaloneta negra estilo baloncesto con script 'New York' y escudo 'NH'.",
  },
  {
    id: "short-wave-navy",
    name: "Pantaloneta Wave Navy",
    category: "Pantalonetas",
    audience: "hombre",
    price: 43900,
    originalPrice: 53900,
    wholesalePrice: 35000,
    wholesaleMinQty: 12,
    image: "/products/pantalonetas/wave-navy.webp",
    sizes: SIZES,
    rating: 4.4,
    reviewCount: 10,
    stock: 100,
    store: STORE,
    description: "Pantaloneta con degradado ondulado azul marino, turquesa y blanco.",
  },
  {
    id: "short-wave-teal",
    name: "Pantaloneta Wave Teal",
    category: "Pantalonetas",
    audience: "hombre",
    price: 43900,
    originalPrice: 53900,
    wholesalePrice: 35000,
    wholesaleMinQty: 12,
    image: "/products/pantalonetas/wave-teal.webp",
    sizes: SIZES,
    rating: 4.4,
    reviewCount: 11,
    stock: 111,
    store: STORE,
    description: "Pantaloneta con degradado ondulado verde jade y menta.",
  },
  {
    id: "short-tiger-blue",
    name: "Pantaloneta Tiger Blue",
    category: "Pantalonetas",
    audience: "hombre",
    price: 46900,
    originalPrice: 56900,
    wholesalePrice: 40000,
    wholesaleMinQty: 12,
    image: "/products/pantalonetas/tiger-blue.webp",
    sizes: SIZES,
    rating: 4.6,
    reviewCount: 15,
    stock: 75,
    store: STORE,
    description: "Pantaloneta azul rey con ilustración tonal de tigre y tipografía 'Tiger'.",
  },
  {
    id: "short-la-23",
    name: "Pantaloneta Los Angeles 23",
    category: "Pantalonetas",
    audience: "hombre",
    price: 47900,
    originalPrice: 57900,
    wholesalePrice: 40000,
    wholesaleMinQty: 12,
    image: "/products/pantalonetas/la-23.webp",
    sizes: SIZES,
    rating: 4.7,
    reviewCount: 24,
    stock: 94,
    store: STORE,
    description: "Pantaloneta petróleo desgastada 'Los Angeles' con número '23' bordado.",
  },
  {
    id: "short-ny-pinstripe",
    name: "Pantaloneta NY Pinstripe Gótica",
    category: "Pantalonetas",
    audience: "hombre",
    price: 46900,
    originalPrice: 56900,
    wholesalePrice: 40000,
    wholesaleMinQty: 12,
    image: "/products/pantalonetas/ny-pinstripe.webp",
    sizes: SIZES,
    rating: 4.5,
    reviewCount: 13,
    stock: 93,
    store: STORE,
    description: "Pantaloneta negra a rayas con monograma gótico 'NY' en ambas piernas.",
  },
  {
    id: "short-negative-grunge",
    name: "Pantaloneta Negative Grunge",
    category: "Pantalonetas",
    audience: "hombre",
    price: 44900,
    originalPrice: 54900,
    wholesalePrice: 35000,
    wholesaleMinQty: 12,
    image: "/products/pantalonetas/negative-grunge.webp",
    sizes: SIZES,
    rating: 4.3,
    reviewCount: 7,
    stock: 97,
    store: STORE,
    description: "Pantaloneta blanca con textura grunge desgastada y gráfica 'Negative'.",
  },
  {
    id: "short-ny-monogram-camo",
    name: "Pantaloneta NY Monogram Camo",
    category: "Pantalonetas",
    audience: "hombre",
    price: 47900,
    originalPrice: 57900,
    wholesalePrice: 40000,
    wholesaleMinQty: 12,
    image: "/products/pantalonetas/ny-monogram-camo.webp",
    sizes: SIZES,
    rating: 4.6,
    reviewCount: 19,
    stock: 119,
    store: STORE,
    description: "Pantaloneta camuflada azul con monograma 'NY' y frase 'Elegance is the product of art'.",
  },
  {
    id: "polo-azul-cielo",
    name: "Polo Azul Cielo",
    category: "Polos",
    audience: "hombre",
    price: 44900,
    originalPrice: 52900,
    wholesalePrice: 37000,
    wholesaleMinQty: 12,
    image: "/products/polos/azul-cielo.webp",
    sizes: SIZES,
    rating: 4.3,
    reviewCount: 12,
    stock: 60,
    store: STORE,
    description: "Polo clásica color azul cielo, tela piqué de algodón, silueta regular.",
  },
  {
    id: "polo-azul-oscuro",
    name: "Polo Azul Oscuro",
    category: "Polos",
    audience: "hombre",
    price: 45900,
    originalPrice: 53900,
    wholesalePrice: 38000,
    wholesaleMinQty: 12,
    image: "/products/polos/azul-oscuro.webp",
    sizes: SIZES,
    rating: 4.4,
    reviewCount: 15,
    stock: 64,
    store: STORE,
    description: "Polo clásica color azul oscuro, tela piqué de algodón, silueta regular.",
  },
  {
    id: "polo-azul-rey",
    name: "Polo Azul Rey",
    category: "Polos",
    audience: "hombre",
    price: 46900,
    originalPrice: 54900,
    wholesalePrice: 38000,
    wholesaleMinQty: 12,
    image: "/products/polos/azul-rey.webp",
    sizes: SIZES,
    rating: 4.5,
    reviewCount: 18,
    stock: 68,
    store: STORE,
    description: "Polo clásica color azul rey, tela piqué de algodón, silueta regular.",
  },
  {
    id: "polo-azul-turquesa",
    name: "Polo Azul Turquesa",
    category: "Polos",
    audience: "hombre",
    price: 47900,
    originalPrice: 55900,
    wholesalePrice: 39000,
    wholesaleMinQty: 12,
    image: "/products/polos/azul-turquesa.webp",
    sizes: SIZES,
    rating: 4.6,
    reviewCount: 21,
    stock: 72,
    store: STORE,
    description: "Polo clásica color azul turquesa, tela piqué de algodón, silueta regular.",
  },
  {
    id: "polo-beige",
    name: "Polo Beige",
    category: "Polos",
    audience: "hombre",
    price: 48900,
    originalPrice: 56900,
    wholesalePrice: 40000,
    wholesaleMinQty: 12,
    image: "/products/polos/beige.webp",
    sizes: SIZES,
    rating: 4.7,
    reviewCount: 24,
    stock: 76,
    store: STORE,
    description: "Polo clásica color beige, tela piqué de algodón, silueta regular.",
  },
  {
    id: "polo-blanca",
    name: "Polo Blanca",
    category: "Polos",
    audience: "hombre",
    price: 44900,
    originalPrice: 52900,
    wholesalePrice: 37000,
    wholesaleMinQty: 12,
    image: "/products/polos/blanca.webp",
    sizes: SIZES,
    rating: 4.3,
    reviewCount: 27,
    stock: 80,
    store: STORE,
    description: "Polo clásica color blanca, tela piqué de algodón, silueta regular.",
  },
  {
    id: "polo-gris-clara",
    name: "Polo Gris Clara",
    category: "Polos",
    audience: "hombre",
    price: 45900,
    originalPrice: 53900,
    wholesalePrice: 38000,
    wholesaleMinQty: 12,
    image: "/products/polos/gris-clara.webp",
    sizes: SIZES,
    rating: 4.4,
    reviewCount: 30,
    stock: 84,
    store: STORE,
    description: "Polo clásica color gris clara, tela piqué de algodón, silueta regular.",
  },
  {
    id: "polo-gris-oscuro",
    name: "Polo Gris Oscuro",
    category: "Polos",
    audience: "hombre",
    price: 46900,
    originalPrice: 54900,
    wholesalePrice: 38000,
    wholesaleMinQty: 12,
    image: "/products/polos/gris-oscuro.webp",
    sizes: SIZES,
    rating: 4.5,
    reviewCount: 33,
    stock: 88,
    store: STORE,
    description: "Polo clásica color gris oscuro, tela piqué de algodón, silueta regular.",
  },
  {
    id: "polo-moradito",
    name: "Polo Morado",
    category: "Polos",
    audience: "hombre",
    price: 47900,
    originalPrice: 55900,
    wholesalePrice: 39000,
    wholesaleMinQty: 12,
    image: "/products/polos/moradito.webp",
    sizes: SIZES,
    rating: 4.6,
    reviewCount: 36,
    stock: 92,
    store: STORE,
    description: "Polo clásica color morado, tela piqué de algodón, silueta regular.",
  },
  {
    id: "polo-mostaza",
    name: "Polo Mostaza",
    category: "Polos",
    audience: "hombre",
    price: 48900,
    originalPrice: 56900,
    wholesalePrice: 40000,
    wholesaleMinQty: 12,
    image: "/products/polos/mostaza.webp",
    sizes: SIZES,
    rating: 4.7,
    reviewCount: 39,
    stock: 96,
    store: STORE,
    description: "Polo clásica color mostaza, tela piqué de algodón, silueta regular.",
  },
  {
    id: "polo-naranja",
    name: "Polo Naranja",
    category: "Polos",
    audience: "hombre",
    price: 44900,
    originalPrice: 52900,
    wholesalePrice: 37000,
    wholesaleMinQty: 12,
    image: "/products/polos/naranja.webp",
    sizes: SIZES,
    rating: 4.3,
    reviewCount: 42,
    stock: 100,
    store: STORE,
    description: "Polo clásica color naranja, tela piqué de algodón, silueta regular.",
  },
  {
    id: "polo-negra",
    name: "Polo Negra",
    category: "Polos",
    audience: "hombre",
    price: 45900,
    originalPrice: 53900,
    wholesalePrice: 38000,
    wholesaleMinQty: 12,
    image: "/products/polos/negra.webp",
    sizes: SIZES,
    rating: 4.4,
    reviewCount: 45,
    stock: 104,
    store: STORE,
    description: "Polo clásica color negra, tela piqué de algodón, silueta regular.",
  },
  {
    id: "polo-rojo",
    name: "Polo Rojo",
    category: "Polos",
    audience: "hombre",
    price: 46900,
    originalPrice: 54900,
    wholesalePrice: 38000,
    wholesaleMinQty: 12,
    image: "/products/polos/rojo.webp",
    sizes: SIZES,
    rating: 4.5,
    reviewCount: 48,
    stock: 108,
    store: STORE,
    description: "Polo clásica color rojo, tela piqué de algodón, silueta regular.",
  },
  {
    id: "polo-rosa",
    name: "Polo Rosa",
    category: "Polos",
    audience: "hombre",
    price: 47900,
    originalPrice: 55900,
    wholesalePrice: 39000,
    wholesaleMinQty: 12,
    image: "/products/polos/rosa.webp",
    sizes: SIZES,
    rating: 4.6,
    reviewCount: 51,
    stock: 112,
    store: STORE,
    description: "Polo clásica color rosa, tela piqué de algodón, silueta regular.",
  },
  {
    id: "polo-verde-flux",
    name: "Polo Verde Flúor",
    category: "Polos",
    audience: "hombre",
    price: 48900,
    originalPrice: 56900,
    wholesalePrice: 40000,
    wholesaleMinQty: 12,
    image: "/products/polos/verde-flux.webp",
    sizes: SIZES,
    rating: 4.7,
    reviewCount: 54,
    stock: 116,
    store: STORE,
    description: "Polo clásica color verde flúor, tela piqué de algodón, silueta regular.",
  },
  {
    id: "polo-verde-militar",
    name: "Polo Verde Militar",
    category: "Polos",
    audience: "hombre",
    price: 44900,
    originalPrice: 52900,
    wholesalePrice: 37000,
    wholesaleMinQty: 12,
    image: "/products/polos/verde-militar.webp",
    sizes: SIZES,
    rating: 4.3,
    reviewCount: 57,
    stock: 120,
    store: STORE,
    description: "Polo clásica color verde militar, tela piqué de algodón, silueta regular.",
  },
  {
    id: "buzo-azul-turquesa",
    name: "Buzo Azul Turquesa",
    category: "Buzos",
    audience: "hombre",
    price: 74900,
    originalPrice: 86900,
    wholesalePrice: 60000,
    wholesaleMinQty: 12,
    image: "/products/buzos/azul-turquesa.webp",
    sizes: SIZES,
    rating: 4.4,
    reviewCount: 10,
    stock: 45,
    store: STORE,
    description: "Buzo con capota color azul turquesa, tela de algodón perchado, bolsillo canguro.",
  },
  {
    id: "buzo-azul",
    name: "Buzo Azul",
    category: "Buzos",
    audience: "hombre",
    price: 76400,
    originalPrice: 88400,
    wholesalePrice: 61000,
    wholesaleMinQty: 12,
    image: "/products/buzos/azul.webp",
    sizes: SIZES,
    rating: 4.5,
    reviewCount: 13,
    stock: 48,
    store: STORE,
    description: "Buzo con capota color azul, tela de algodón perchado, bolsillo canguro.",
  },
  {
    id: "buzo-beige",
    name: "Buzo Beige",
    category: "Buzos",
    audience: "hombre",
    price: 77900,
    originalPrice: 89900,
    wholesalePrice: 62000,
    wholesaleMinQty: 12,
    image: "/products/buzos/beige.webp",
    sizes: SIZES,
    rating: 4.6,
    reviewCount: 16,
    stock: 51,
    store: STORE,
    description: "Buzo con capota color beige, tela de algodón perchado, bolsillo canguro.",
  },
  {
    id: "buzo-blanco",
    name: "Buzo Blanco",
    category: "Buzos",
    audience: "hombre",
    price: 79400,
    originalPrice: 91400,
    wholesalePrice: 64000,
    wholesaleMinQty: 12,
    image: "/products/buzos/blanco.webp",
    sizes: SIZES,
    rating: 4.7,
    reviewCount: 19,
    stock: 54,
    store: STORE,
    description: "Buzo con capota color blanco, tela de algodón perchado, bolsillo canguro.",
  },
  {
    id: "buzo-gris",
    name: "Buzo Gris",
    category: "Buzos",
    audience: "hombre",
    price: 80900,
    originalPrice: 92900,
    wholesalePrice: 65000,
    wholesaleMinQty: 12,
    image: "/products/buzos/gris.webp",
    sizes: SIZES,
    rating: 4.4,
    reviewCount: 22,
    stock: 57,
    store: STORE,
    description: "Buzo con capota color gris, tela de algodón perchado, bolsillo canguro.",
  },
  {
    id: "buzo-morado-claro",
    name: "Buzo Morado Claro",
    category: "Buzos",
    audience: "hombre",
    price: 82400,
    originalPrice: 94400,
    wholesalePrice: 66000,
    wholesaleMinQty: 12,
    image: "/products/buzos/morado-claro.webp",
    sizes: SIZES,
    rating: 4.5,
    reviewCount: 25,
    stock: 60,
    store: STORE,
    description: "Buzo con capota color morado claro, tela de algodón perchado, bolsillo canguro.",
  },
  {
    id: "buzo-morado-oscuro",
    name: "Buzo Morado Oscuro",
    category: "Buzos",
    audience: "hombre",
    price: 74900,
    originalPrice: 86900,
    wholesalePrice: 60000,
    wholesaleMinQty: 12,
    image: "/products/buzos/morado-oscuro.webp",
    sizes: SIZES,
    rating: 4.6,
    reviewCount: 28,
    stock: 63,
    store: STORE,
    description: "Buzo con capota color morado oscuro, tela de algodón perchado, bolsillo canguro.",
  },
  {
    id: "buzo-mostaza",
    name: "Buzo Mostaza",
    category: "Buzos",
    audience: "hombre",
    price: 76400,
    originalPrice: 88400,
    wholesalePrice: 61000,
    wholesaleMinQty: 12,
    image: "/products/buzos/mostaza.webp",
    sizes: SIZES,
    rating: 4.7,
    reviewCount: 31,
    stock: 66,
    store: STORE,
    description: "Buzo con capota color mostaza, tela de algodón perchado, bolsillo canguro.",
  },
  {
    id: "buzo-naranja",
    name: "Buzo Naranja",
    category: "Buzos",
    audience: "hombre",
    price: 77900,
    originalPrice: 89900,
    wholesalePrice: 62000,
    wholesaleMinQty: 12,
    image: "/products/buzos/naranja.webp",
    sizes: SIZES,
    rating: 4.4,
    reviewCount: 34,
    stock: 69,
    store: STORE,
    description: "Buzo con capota color naranja, tela de algodón perchado, bolsillo canguro.",
  },
  {
    id: "buzo-negro",
    name: "Buzo Negro",
    category: "Buzos",
    audience: "hombre",
    price: 79400,
    originalPrice: 91400,
    wholesalePrice: 64000,
    wholesaleMinQty: 12,
    image: "/products/buzos/negro.webp",
    sizes: SIZES,
    rating: 4.5,
    reviewCount: 37,
    stock: 72,
    store: STORE,
    description: "Buzo con capota color negro, tela de algodón perchado, bolsillo canguro.",
  },
  {
    id: "buzo-pastel",
    name: "Buzo Pastel",
    category: "Buzos",
    audience: "hombre",
    price: 80900,
    originalPrice: 92900,
    wholesalePrice: 65000,
    wholesaleMinQty: 12,
    image: "/products/buzos/pastel.webp",
    sizes: SIZES,
    rating: 4.6,
    reviewCount: 40,
    stock: 75,
    store: STORE,
    description: "Buzo con capota color pastel, tela de algodón perchado, bolsillo canguro.",
  },
  {
    id: "buzo-rosa-claro",
    name: "Buzo Rosa Claro",
    category: "Buzos",
    audience: "hombre",
    price: 82400,
    originalPrice: 94400,
    wholesalePrice: 66000,
    wholesaleMinQty: 12,
    image: "/products/buzos/rosa-claro.webp",
    sizes: SIZES,
    rating: 4.7,
    reviewCount: 43,
    stock: 78,
    store: STORE,
    description: "Buzo con capota color rosa claro, tela de algodón perchado, bolsillo canguro.",
  },
  {
    id: "buzo-rosa",
    name: "Buzo Rosa",
    category: "Buzos",
    audience: "hombre",
    price: 74900,
    originalPrice: 86900,
    wholesalePrice: 60000,
    wholesaleMinQty: 12,
    image: "/products/buzos/rosa.webp",
    sizes: SIZES,
    rating: 4.4,
    reviewCount: 46,
    stock: 81,
    store: STORE,
    description: "Buzo con capota color rosa, tela de algodón perchado, bolsillo canguro.",
  },
  {
    id: "buzo-verde-militar",
    name: "Buzo Verde Militar",
    category: "Buzos",
    audience: "hombre",
    price: 76400,
    originalPrice: 88400,
    wholesalePrice: 61000,
    wholesaleMinQty: 12,
    image: "/products/buzos/verde-militar.webp",
    sizes: SIZES,
    rating: 4.5,
    reviewCount: 49,
    stock: 84,
    store: STORE,
    description: "Buzo con capota color verde militar, tela de algodón perchado, bolsillo canguro.",
  },
  {
    id: "nino-dragon-ball-z",
    name: "Camiseta Dragon Ball Z",
    category: "Camisetas",
    audience: "hombre",
    price: 47900,
    originalPrice: 57900,
    wholesalePrice: 40000,
    wholesaleMinQty: 12,
    image: "/products/ninos/dragon-ball-z.webp",
    sizes: SIZES,
    rating: 4.8,
    reviewCount: 22,
    stock: 64,
    store: STORE,
    description: "Camiseta blanca con estampado de Dragon Ball Z, Goku y las esferas del dragón.",
  },
  {
    id: "nino-lilo-stitch",
    name: "Camiseta Lilo & Stitch",
    category: "Camisetas",
    audience: "hombre",
    price: 47900,
    originalPrice: 57900,
    wholesalePrice: 40000,
    wholesaleMinQty: 12,
    image: "/products/ninos/lilo-stitch.webp",
    sizes: SIZES,
    rating: 4.9,
    reviewCount: 35,
    stock: 71,
    store: STORE,
    description: "Camiseta crema con estampado de Stitch estilo urbano y logo 'Lilo & Stitch'.",
  },
  {
    id: "nino-batman",
    name: "Camiseta Batman",
    category: "Camisetas",
    audience: "hombre",
    price: 47900,
    originalPrice: 57900,
    wholesalePrice: 40000,
    wholesaleMinQty: 12,
    image: "/products/ninos/batman.webp",
    sizes: SIZES,
    rating: 4.7,
    reviewCount: 18,
    stock: 58,
    store: STORE,
    description: "Camiseta color crudo con estampado gráfico de Batman y el logo del murciélago.",
  },
  {
    id: "nino-muttik-skater",
    name: "Camiseta Muttik Skater",
    category: "Camisetas",
    audience: "hombre",
    price: 46900,
    originalPrice: 56900,
    wholesalePrice: 39000,
    wholesaleMinQty: 12,
    image: "/products/ninos/muttik-skater.webp",
    sizes: SIZES,
    rating: 4.6,
    reviewCount: 14,
    stock: 52,
    store: STORE,
    description: "Camiseta negra con estampado de conejo skater 'Muttik Silver Attack', estilo urbano.",
  },
  {
    id: "nino-spongebob-crazy-beige",
    name: "Camiseta SpongeBob Crazy (Beige)",
    category: "Camisetas",
    audience: "hombre",
    price: 47900,
    originalPrice: 57900,
    wholesalePrice: 40000,
    wholesaleMinQty: 12,
    image: "/products/ninos/spongebob-crazy-beige.webp",
    sizes: SIZES,
    rating: 4.8,
    reviewCount: 27,
    stock: 66,
    store: STORE,
    description: "Camiseta beige con estampado grafiti de Bob Esponja saltando, 'Crazy Sponge Bob'.",
  },
  {
    id: "nino-stitch-lima",
    name: "Camiseta Stitch Lima",
    category: "Camisetas",
    audience: "mujer",
    price: 57900,
    originalPrice: 67900,
    wholesalePrice: 47000,
    wholesaleMinQty: 12,
    image: "/products/ninos/stitch-lima.webp",
    sizes: SIZES,
    rating: 4.9,
    reviewCount: 41,
    stock: 78,
    store: STORE,
    description: "Camiseta verde lima con estampado de Stitch sentado y letras rosadas.",
  },
  {
    id: "nino-spongebob-crazy-morado",
    name: "Camiseta SpongeBob Crazy (Morado)",
    category: "Camisetas",
    audience: "hombre",
    price: 47900,
    originalPrice: 57900,
    wholesalePrice: 40000,
    wholesaleMinQty: 12,
    image: "/products/ninos/spongebob-crazy-morado.webp",
    sizes: SIZES,
    rating: 4.7,
    reviewCount: 20,
    stock: 61,
    store: STORE,
    description: "Camiseta morada con estampado grafiti de Bob Esponja saltando, 'Crazy Sponge Bob'.",
  },
  {
    id: "nino-mickey-fisherman",
    name: "Camiseta Mickey Mouse Pescador",
    category: "Camisetas",
    audience: "mujer",
    price: 57900,
    originalPrice: 67900,
    wholesalePrice: 47000,
    wholesaleMinQty: 12,
    image: "/products/ninos/mickey-fisherman.webp",
    sizes: SIZES,
    rating: 4.8,
    reviewCount: 30,
    stock: 69,
    store: STORE,
    description: "Camiseta verde menta con estampado de Mickey Mouse pescador y logo 'Mickey Mouse'.",
  },
  {
    id: "nino-mickey-friends",
    name: "Camiseta Mickey Friends",
    category: "Camisetas",
    audience: "hombre",
    price: 49900,
    originalPrice: 59900,
    wholesalePrice: 42000,
    wholesaleMinQty: 12,
    image: "/products/ninos/mickey-friends.webp",
    backImage: "/products/ninos/mickey-friends-back.webp",
    sizes: SIZES,
    rating: 4.9,
    reviewCount: 25,
    stock: 57,
    store: STORE,
    description: "Camiseta verde oliva con estampado 'Mickey' al frente y 'Friends don't lie' en la espalda.",
  },

  {
    id: "cm-28-massachusetts",
    name: "Camiseta Oversize 28 Massachusetts",
    category: "Camisetas",
    audience: "mujer",
    price: 58900,
    originalPrice: 68900,
    wholesalePrice: 48000,
    wholesaleMinQty: 12,
    image: "/products/camisetas-mujer/28-massachusetts.webp",
    backImage: "/products/camisetas-mujer/28-massachusetts-back.webp",
    sizes: SIZES,
    rating: 4.6,
    reviewCount: 17,
    stock: 74,
    store: STORE,
    description: "Camiseta oversize con estampado universitario '28 Massachusetts', frente y espalda a juego.",
  },
  {
    id: "cm-mickey-cafe",
    name: "Camiseta Oversize Mickey Original",
    category: "Camisetas",
    audience: "mujer",
    price: 59900,
    originalPrice: 69900,
    wholesalePrice: 49000,
    wholesaleMinQty: 12,
    image: "/products/camisetas-mujer/mickey-cafe.webp",
    backImage: "/products/camisetas-mujer/mickey-cafe-back.webp",
    sizes: SIZES,
    rating: 4.7,
    reviewCount: 22,
    stock: 68,
    store: STORE,
    description: "Camiseta oversize color crema con estampado de corazones y tres bocetos de Mickey Mouse, texto 'The Original, One and Only'.",
  },
  {
    id: "cm-scooby-doo",
    name: "Camiseta Oversize Scooby-Doo Adventures",
    category: "Camisetas",
    audience: "mujer",
    price: 59900,
    originalPrice: 69900,
    wholesalePrice: 49000,
    wholesaleMinQty: 12,
    image: "/products/camisetas-mujer/scooby-doo.webp",
    backImage: "/products/camisetas-mujer/scooby-doo-back.webp",
    sizes: SIZES,
    rating: 4.8,
    reviewCount: 29,
    stock: 71,
    store: STORE,
    description: "Camiseta oversize blanca y azul estilo universitario con el elenco de Scooby-Doo y el texto 'Zoinks!'.",
  },
  {
    id: "cm-silvestre",
    name: "Camiseta Oversize Silvestre",
    category: "Camisetas",
    audience: "mujer",
    price: 58900,
    originalPrice: 68900,
    wholesalePrice: 48000,
    wholesaleMinQty: 12,
    image: "/products/camisetas-mujer/silvestre.webp",
    backImage: "/products/camisetas-mujer/silvestre-back.webp",
    sizes: SIZES,
    rating: 4.7,
    reviewCount: 20,
    stock: 65,
    store: STORE,
    description: "Camiseta oversize blanca y negra con primer plano de Silvestre y logo 'Looney Tunes'.",
  },
  {
    id: "cm-betty-boop",
    name: "Camiseta Oversize Betty Boop Dodgers",
    category: "Camisetas",
    audience: "mujer",
    price: 59900,
    originalPrice: 69900,
    wholesalePrice: 49000,
    wholesaleMinQty: 12,
    image: "/products/camisetas-mujer/betty-boop.webp",
    backImage: "/products/camisetas-mujer/betty-boop-back.webp",
    sizes: SIZES,
    rating: 4.6,
    reviewCount: 15,
    stock: 59,
    store: STORE,
    description: "Camiseta oversize negra a rayas estilo béisbol con Betty Boop y gorra deportiva.",
  },
  {
    id: "cm-betty-boop-morada",
    name: "Camiseta Oversize Betty Boop Biker",
    category: "Camisetas",
    audience: "mujer",
    price: 59900,
    originalPrice: 69900,
    wholesalePrice: 49000,
    wholesaleMinQty: 12,
    image: "/products/camisetas-mujer/betty-boop-morada.webp",
    backImage: "/products/camisetas-mujer/betty-boop-morada-back.webp",
    sizes: SIZES,
    rating: 4.7,
    reviewCount: 18,
    stock: 62,
    store: STORE,
    description: "Camiseta oversize blanca con mangas moradas, Betty Boop en moto con llamas y letras 'Betty' en vertical.",
  },
  {
    id: "cm-bob-dog",
    name: "Camiseta Oversize Bob Dog",
    category: "Camisetas",
    audience: "mujer",
    price: 58900,
    originalPrice: 68900,
    wholesalePrice: 48000,
    wholesaleMinQty: 12,
    image: "/products/camisetas-mujer/bob-dog.webp",
    backImage: "/products/camisetas-mujer/bob-dog-back.webp",
    sizes: SIZES,
    rating: 4.5,
    reviewCount: 12,
    stock: 55,
    store: STORE,
    description: "Camiseta oversize roja con personaje 'Bob Dog' y texto repetido 'Little Primitive' de fondo.",
  },
  {
    id: "cm-brooklyn",
    name: "Camiseta Oversize Brooklyn Genius",
    category: "Camisetas",
    audience: "mujer",
    price: 58900,
    originalPrice: 68900,
    wholesalePrice: 48000,
    wholesaleMinQty: 12,
    image: "/products/camisetas-mujer/brooklyn-oversize.webp",
    backImage: "/products/camisetas-mujer/brooklyn-oversize-back.webp",
    sizes: SIZES,
    rating: 4.6,
    reviewCount: 16,
    stock: 60,
    store: STORE,
    description: "Camiseta oversize gris jaspeado con mangas raglán y estampado universitario 'Brooklyn Genius'.",
  },
  {
    id: "cm-bugs-bunny",
    name: "Camiseta Oversize Bugs Bunny",
    category: "Camisetas",
    audience: "mujer",
    price: 59900,
    originalPrice: 69900,
    wholesalePrice: 49000,
    wholesaleMinQty: 12,
    image: "/products/camisetas-mujer/bugs-bunny-oversize.webp",
    backImage: "/products/camisetas-mujer/bugs-bunny-oversize-back.webp",
    sizes: SIZES,
    rating: 4.8,
    reviewCount: 26,
    stock: 70,
    store: STORE,
    description: "Camiseta oversize gris con primer plano de Bugs Bunny y logos Warner Bros. de fondo.",
  },
  {
    id: "cm-bunny-queen",
    name: "Camiseta Oversize Bunny Queen",
    category: "Camisetas",
    audience: "mujer",
    price: 58900,
    originalPrice: 68900,
    wholesalePrice: 48000,
    wholesaleMinQty: 12,
    image: "/products/camisetas-mujer/bunny-queen.webp",
    backImage: "/products/camisetas-mujer/bunny-queen-back.webp",
    sizes: SIZES,
    rating: 4.5,
    reviewCount: 11,
    stock: 53,
    store: STORE,
    description: "Camiseta oversize negra efecto tie-dye con coneja estilo rockera y grafiti de fondo.",
  },
  {
    id: "cm-california-rosa",
    name: "Camiseta Oversize California Vintage",
    category: "Camisetas",
    audience: "mujer",
    price: 58900,
    originalPrice: 68900,
    wholesalePrice: 48000,
    wholesaleMinQty: 12,
    image: "/products/camisetas-mujer/california-rosa.webp",
    backImage: "/products/camisetas-mujer/california-rosa-back.webp",
    sizes: SIZES,
    rating: 4.6,
    reviewCount: 19,
    stock: 64,
    store: STORE,
    description: "Camiseta oversize rosa con estampado animal print y texto 'California Vintage'.",
  },
  {
    id: "cm-cherry",
    name: "Camiseta Oversize Cherry Berry Days",
    category: "Camisetas",
    audience: "mujer",
    price: 58900,
    originalPrice: 68900,
    wholesalePrice: 48000,
    wholesaleMinQty: 12,
    image: "/products/camisetas-mujer/cherry.webp",
    backImage: "/products/camisetas-mujer/cherry-back.webp",
    sizes: SIZES,
    rating: 4.7,
    reviewCount: 21,
    stock: 66,
    store: STORE,
    description: "Camiseta oversize a rayas rosa y azul efecto denim con cerezas y texto 'Cherry Berry Days'.",
  },
  {
    id: "cm-cherry-black",
    name: "Camiseta Oversize Cherry Black",
    category: "Camisetas",
    audience: "mujer",
    price: 58900,
    originalPrice: 68900,
    wholesalePrice: 48000,
    wholesaleMinQty: 12,
    image: "/products/camisetas-mujer/cherry-black.webp",
    backImage: "/products/camisetas-mujer/cherry-black-back.webp",
    sizes: SIZES,
    rating: 4.6,
    reviewCount: 14,
    stock: 57,
    store: STORE,
    description: "Camiseta oversize negra con cerezas animal print rosa y texto 'Cherry'.",
  },
  {
    id: "cm-corazones-azules",
    name: "Camiseta Oversize Corazones Azules",
    category: "Camisetas",
    audience: "mujer",
    price: 57900,
    originalPrice: 67900,
    wholesalePrice: 47000,
    wholesaleMinQty: 12,
    image: "/products/camisetas-mujer/corazones-azules.webp",
    backImage: "/products/camisetas-mujer/corazones-azules-back.webp",
    sizes: SIZES,
    rating: 4.7,
    reviewCount: 23,
    stock: 69,
    store: STORE,
    description: "Camiseta oversize blanca con corazones efecto denim y mensaje 'Love and Hope'.",
  },
  {
    id: "cm-denim",
    name: "Camiseta Oversize Denim Monograma",
    category: "Camisetas",
    audience: "mujer",
    price: 59900,
    originalPrice: 69900,
    wholesalePrice: 49000,
    wholesaleMinQty: 12,
    image: "/products/camisetas-mujer/denim-oversize.webp",
    backImage: "/products/camisetas-mujer/denim-oversize-back.webp",
    sizes: SIZES,
    rating: 4.5,
    reviewCount: 13,
    stock: 56,
    store: STORE,
    description: "Camiseta oversize efecto denim desgastado con estampado de monograma y corazones, detalle roto en los hombros.",
  },
  {
    id: "cm-garfield",
    name: "Camiseta Oversize Garfield",
    category: "Camisetas",
    audience: "mujer",
    price: 58900,
    originalPrice: 68900,
    wholesalePrice: 48000,
    wholesaleMinQty: 12,
    image: "/products/camisetas-mujer/garfield.webp",
    backImage: "/products/camisetas-mujer/garfield-back.webp",
    sizes: SIZES,
    rating: 4.6,
    reviewCount: 17,
    stock: 61,
    store: STORE,
    description: "Camiseta oversize negra con estampado geométrico y Garfield en chaqueta universitaria, texto 'Don't Know, Don't Care'.",
  },
  {
    id: "cm-gotico-rosa",
    name: "Camiseta Oversize Gótica Snow White",
    category: "Camisetas",
    audience: "mujer",
    price: 58900,
    originalPrice: 68900,
    wholesalePrice: 48000,
    wholesaleMinQty: 12,
    image: "/products/camisetas-mujer/gotico-rosa.webp",
    backImage: "/products/camisetas-mujer/gotico-rosa-back.webp",
    sizes: SIZES,
    rating: 4.5,
    reviewCount: 12,
    stock: 54,
    store: STORE,
    description: "Camiseta oversize fucsia efecto grunge con manzana mordida y texto grafiti 'Snow White'.",
  },
  {
    id: "cm-hello-kitty",
    name: "Camiseta Oversize Hello Kitty",
    category: "Camisetas",
    audience: "mujer",
    price: 59900,
    originalPrice: 69900,
    wholesalePrice: 49000,
    wholesaleMinQty: 12,
    image: "/products/camisetas-mujer/hello-kitty.webp",
    backImage: "/products/camisetas-mujer/hello-kitty-back.webp",
    sizes: SIZES,
    rating: 4.8,
    reviewCount: 31,
    stock: 76,
    store: STORE,
    description: "Camiseta oversize blanca con estampado de Hello Kitty en tonos pastel, frente y espalda a juego.",
  },
  {
    id: "cm-mickey-mini",
    name: "Camiseta Oversize Mickey y Minnie",
    category: "Camisetas",
    audience: "mujer",
    price: 58900,
    originalPrice: 68900,
    wholesalePrice: 48000,
    wholesaleMinQty: 12,
    image: "/products/camisetas-mujer/mickey-mini.webp",
    backImage: "/products/camisetas-mujer/mickey-mini-back.webp",
    sizes: SIZES,
    rating: 4.7,
    reviewCount: 20,
    stock: 63,
    store: STORE,
    description: "Camiseta oversize gris oscuro con corazones y Mickey y Minnie dándose un beso.",
  },
  {
    id: "cm-minnie-mouse",
    name: "Camiseta Oversize Minnie Mouse",
    category: "Camisetas",
    audience: "mujer",
    price: 58900,
    originalPrice: 68900,
    wholesalePrice: 48000,
    wholesaleMinQty: 12,
    image: "/products/camisetas-mujer/minnie-mouse.webp",
    backImage: "/products/camisetas-mujer/minnie-mouse-back.webp",
    sizes: SIZES,
    rating: 4.6,
    reviewCount: 16,
    stock: 58,
    store: STORE,
    description: "Camiseta oversize efecto degradé con texto 'Minnie' y tres viñetas de Minnie Mouse.",
  },
  {
    id: "cm-new-york-usa",
    name: "Camiseta Oversize New York City USA",
    category: "Camisetas",
    audience: "mujer",
    price: 57900,
    originalPrice: 67900,
    wholesalePrice: 47000,
    wholesaleMinQty: 12,
    image: "/products/camisetas-mujer/new-york-usa.webp",
    backImage: "/products/camisetas-mujer/new-york-usa-back.webp",
    sizes: SIZES,
    rating: 4.6,
    reviewCount: 18,
    stock: 62,
    store: STORE,
    description: "Camiseta oversize rosa efecto mármol con estampado grafiti 'New York City USA'.",
  },
  {
    id: "cm-oso-arcoiris",
    name: "Camiseta Oversize Oso Care Bears",
    category: "Camisetas",
    audience: "mujer",
    price: 58900,
    originalPrice: 68900,
    wholesalePrice: 48000,
    wholesaleMinQty: 12,
    image: "/products/camisetas-mujer/oso-arcoiris.webp",
    backImage: "/products/camisetas-mujer/oso-arcoiris-back.webp",
    sizes: SIZES,
    rating: 4.6,
    reviewCount: 15,
    stock: 59,
    store: STORE,
    description: "Camiseta oversize azul estilo universitario número '82' con oso de anteojos y logo 'Care Bears'.",
  },
  {
    id: "cm-oso-azul",
    name: "Camiseta Oversize Oso Good Love",
    category: "Camisetas",
    audience: "mujer",
    price: 57900,
    originalPrice: 67900,
    wholesalePrice: 47000,
    wholesaleMinQty: 12,
    image: "/products/camisetas-mujer/oso-azul.webp",
    backImage: "/products/camisetas-mujer/oso-azul-back.webp",
    sizes: SIZES,
    rating: 4.5,
    reviewCount: 13,
    stock: 55,
    store: STORE,
    description: "Camiseta oversize azul efecto denim con oso de gorro y riñonera, texto 'Good Love'.",
  },
  {
    id: "cm-oso-cafe",
    name: "Camiseta Oversize Oso Just Smile",
    category: "Camisetas",
    audience: "mujer",
    price: 57900,
    originalPrice: 67900,
    wholesalePrice: 47000,
    wholesaleMinQty: 12,
    image: "/products/camisetas-mujer/oso-cafe.webp",
    backImage: "/products/camisetas-mujer/oso-cafe-back.webp",
    sizes: SIZES,
    rating: 4.6,
    reviewCount: 14,
    stock: 57,
    store: STORE,
    description: "Camiseta oversize a rayas café y blanco con oso de gorro y texto 'Just Smile'.",
  },
  {
    id: "cm-piolin",
    name: "Camiseta Oversize Piolín Brooklyn",
    category: "Camisetas",
    audience: "mujer",
    price: 58900,
    originalPrice: 68900,
    wholesalePrice: 48000,
    wholesaleMinQty: 12,
    image: "/products/camisetas-mujer/piolin.webp",
    backImage: "/products/camisetas-mujer/piolin-back.webp",
    sizes: SIZES,
    rating: 4.7,
    reviewCount: 22,
    stock: 65,
    store: STORE,
    description: "Camiseta oversize amarilla a rayas con Piolín saltando y estampado 'Tweety Brooklyn'.",
  },
  {
    id: "cm-power-chicas",
    name: "Camiseta Oversize Chicas Superpoderosas",
    category: "Camisetas",
    audience: "mujer",
    price: 58900,
    originalPrice: 68900,
    wholesalePrice: 48000,
    wholesaleMinQty: 12,
    image: "/products/camisetas-mujer/power-chicas.webp",
    backImage: "/products/camisetas-mujer/power-chicas-back.webp",
    sizes: SIZES,
    rating: 4.8,
    reviewCount: 27,
    stock: 71,
    store: STORE,
    description: "Camiseta oversize rosa y negra con las Chicas Superpoderosas de porristas y logo 'PPG'.",
  },
  {
    id: "cm-rosa",
    name: "Camiseta Oversize Pink Deportivo",
    category: "Camisetas",
    audience: "mujer",
    price: 57900,
    originalPrice: 67900,
    wholesalePrice: 47000,
    wholesaleMinQty: 12,
    image: "/products/camisetas-mujer/rosa-oversize.webp",
    backImage: "/products/camisetas-mujer/rosa-oversize-back.webp",
    sizes: SIZES,
    rating: 4.5,
    reviewCount: 12,
    stock: 52,
    store: STORE,
    description: "Camiseta oversize rosa estilo deportivo universitario con número '22' y texto 'Pink Deportivo'.",
  },
  {
    id: "cm-tigre-rosa",
    name: "Camiseta Oversize Tigre Cool",
    category: "Camisetas",
    audience: "mujer",
    price: 57900,
    originalPrice: 67900,
    wholesalePrice: 47000,
    wholesaleMinQty: 12,
    image: "/products/camisetas-mujer/tigre-rosa.webp",
    backImage: "/products/camisetas-mujer/tigre-rosa-back.webp",
    sizes: SIZES,
    rating: 4.6,
    reviewCount: 16,
    stock: 58,
    store: STORE,
    description: "Camiseta oversize rosa pálido con tigre de gafas y chicle, texto 'Cool' repetido de fondo.",
  },
  {
    id: "cm-tom-jerry-rosa",
    name: "Camiseta Oversize Tom and Jerry BFF",
    category: "Camisetas",
    audience: "mujer",
    price: 58900,
    originalPrice: 68900,
    wholesalePrice: 48000,
    wholesaleMinQty: 12,
    image: "/products/camisetas-mujer/tom-jerry-rosa.webp",
    backImage: "/products/camisetas-mujer/tom-jerry-rosa-back.webp",
    sizes: SIZES,
    rating: 4.7,
    reviewCount: 19,
    stock: 63,
    store: STORE,
    description: "Camiseta oversize blanca con mangas rosas, Tom y Jerry y texto 'BFF Tom and Jerry'.",
  },
  {
    id: "cm-oveja",
    name: "Camiseta Oversize Ovejita",
    category: "Camisetas",
    audience: "mujer",
    price: 54900,
    originalPrice: 63900,
    wholesalePrice: 44000,
    wholesaleMinQty: 12,
    image: "/products/camisetas-mujer/oveja.webp",
    sizes: SIZES,
    rating: 4.6,
    reviewCount: 14,
    stock: 56,
    store: STORE,
    description: "Camiseta oversize blanca con parche de ovejita en relieve, diseño minimalista.",
  },
  {
    id: "cm-unknown-gris",
    name: "Camiseta Oversize Unknown Gris",
    category: "Camisetas",
    audience: "mujer",
    price: 54900,
    originalPrice: 63900,
    wholesalePrice: 44000,
    wholesaleMinQty: 12,
    image: "/products/camisetas-mujer/unknown-gris.webp",
    sizes: SIZES,
    rating: 4.4,
    reviewCount: 9,
    stock: 47,
    store: STORE,
    description: "Camiseta oversize gris y blanca con silueta de sombrero y gafas, texto 'Unknown'.",
  },
  {
    id: "cm-estrellas-perla",
    name: "Camiseta Oversize Estrellas y Perlas",
    category: "Camisetas",
    audience: "mujer",
    price: 55900,
    originalPrice: 64900,
    wholesalePrice: 45000,
    wholesaleMinQty: 12,
    image: "/products/camisetas-mujer/estrellas-perla.webp",
    sizes: SIZES,
    rating: 4.5,
    reviewCount: 11,
    stock: 49,
    store: STORE,
    description: "Camiseta oversize blanca con estampado de estrellas y broche floral de perlas al pecho.",
  },
  {
    id: "cm-unknown-negra",
    name: "Camiseta Oversize Unknown Negra",
    category: "Camisetas",
    audience: "mujer",
    price: 54900,
    originalPrice: 63900,
    wholesalePrice: 44000,
    wholesaleMinQty: 12,
    image: "/products/camisetas-mujer/unknown-negra.webp",
    sizes: SIZES,
    rating: 4.4,
    reviewCount: 8,
    stock: 45,
    store: STORE,
    description: "Camiseta oversize negra y blanca con silueta de sombrero y gafas, estilo urbano.",
  },
  {
    id: "cm-time-is-precious",
    name: "Camiseta Oversize Time is Precious",
    category: "Camisetas",
    audience: "mujer",
    price: 55900,
    originalPrice: 64900,
    wholesalePrice: 45000,
    wholesaleMinQty: 12,
    image: "/products/camisetas-mujer/time-is-precious.webp",
    sizes: SIZES,
    rating: 4.6,
    reviewCount: 15,
    stock: 53,
    store: STORE,
    description: "Camiseta oversize negra con reloj de arena y texto 'Time is Precious'.",
  },
  {
    id: "cm-pedreria-vino",
    name: "Camiseta Oversize Pedrería Vino",
    category: "Camisetas",
    audience: "mujer",
    price: 56900,
    originalPrice: 65900,
    wholesalePrice: 46000,
    wholesaleMinQty: 12,
    image: "/products/camisetas-mujer/pedreria-vino.webp",
    sizes: SIZES,
    rating: 4.5,
    reviewCount: 10,
    stock: 46,
    store: STORE,
    description: "Camiseta oversize vinotinto con pedrería dorada en los hombros.",
  },
  {
    id: "ch-venado",
    name: "Camiseta Oversize Venado",
    category: "Camisetas",
    audience: "hombre",
    price: 59900,
    originalPrice: 69900,
    wholesalePrice: 49000,
    wholesaleMinQty: 12,
    image: "/products/camisetas-hombre/venado.webp",
    backImage: "/products/camisetas-hombre/venado-back.webp",
    sizes: SIZES,
    rating: 4.7,
    reviewCount: 24,
    stock: 68,
    store: STORE,
    description: "Camiseta oversize verde militar con silueta de venado al frente y gran estampado gráfico de venado con tipografía en la espalda.",
  },
  {
    id: "blusa-rosa-palo",
    name: "Blusa Halter Rosa Palo",
    category: "Blusas",
    audience: "mujer",
    price: 46900,
    originalPrice: 55900,
    wholesalePrice: 37000,
    wholesaleMinQty: 12,
    image: "/products/blusas/blusa-rosa-palo.webp",
    sizes: SIZES,
    rating: 4.5,
    reviewCount: 13,
    stock: 48,
    store: STORE,
    description: "Blusa halter en gasa color durazno, silueta globo con vuelo en la parte inferior.",
  },
  {
    id: "camisa-pedreria-blanca",
    name: "Camisa Blanca Pedrería Dorada",
    category: "Camisas",
    audience: "mujer",
    price: 64900,
    originalPrice: 74900,
    wholesalePrice: 54000,
    wholesaleMinQty: 12,
    image: "/products/camisas-dama/camisa-pedreria-blanca.webp",
    sizes: SIZES,
    rating: 4.7,
    reviewCount: 19,
    stock: 51,
    store: STORE,
    description: "Camisa blanca de botones con pedrería dorada en la pechera y las mangas, cuello clásico.",
  },
  {
    id: "camisa-encaje-negra",
    name: "Camisa Negra Encaje y Perlas",
    category: "Camisas",
    audience: "mujer",
    price: 62900,
    originalPrice: 72900,
    wholesalePrice: 52000,
    wholesaleMinQty: 12,
    image: "/products/camisas-dama/camisa-encaje-negra.webp",
    sizes: SIZES,
    rating: 4.6,
    reviewCount: 16,
    stock: 47,
    store: STORE,
    description: "Camisa negra de botones con encaje y perlas en el canesú, mangas 3/4 remangables.",
  },
  {
    id: "nina-stitch-comic",
    name: "Camiseta Stitch Comic Niñas",
    category: "Niños",
    audience: "nina",
    price: 44900,
    originalPrice: 52900,
    wholesalePrice: 36000,
    wholesaleMinQty: 12,
    image: "/products/ninos/nina-stitch-comic.webp",
    backImage: "/products/ninos/nina-stitch-comic-back.webp",
    sizes: KIDS_SIZES,
    rating: 4.8,
    reviewCount: 21,
    stock: 60,
    store: STORE,
    description: "Camiseta infantil degradé azul y rosa con mini estampado 'Lilo & Stitch' al frente y viñetas de Stitch en la espalda.",
  },
  {
    id: "nino-mario-bros",
    name: "Camiseta Super Mario Bros Niño",
    category: "Niños",
    audience: "nino",
    price: 44900,
    originalPrice: 52900,
    wholesalePrice: 36000,
    wholesaleMinQty: 12,
    image: "/products/ninos/nino-mario-bros.webp",
    backImage: "/products/ninos/nino-mario-bros-back.webp",
    sizes: KIDS_SIZES,
    rating: 4.8,
    reviewCount: 25,
    stock: 64,
    store: STORE,
    description: "Camiseta infantil roja con icono de hongo en bloque de interrogación al frente y gran estampado de Mario Bros en la espalda.",
  },
  {
    id: "nino-lancer-evo",
    name: "Camiseta Lancer Evolution Niño",
    category: "Niños",
    audience: "nino",
    price: 44900,
    originalPrice: 52900,
    wholesalePrice: 36000,
    wholesaleMinQty: 12,
    image: "/products/ninos/nino-lancer-evo.webp",
    backImage: "/products/ninos/nino-lancer-evo-back.webp",
    sizes: KIDS_SIZES,
    rating: 4.7,
    reviewCount: 18,
    stock: 56,
    store: STORE,
    description: "Camiseta infantil negra jaspeada con logo 'Lancer Evolution' al frente y gran estampado del auto de carreras en la espalda.",
  },
  {
    id: "ninas-minnie-daisy",
    name: "Camiseta Minnie & Daisy Niñas",
    category: "Niños",
    audience: "nina",
    price: 44900,
    originalPrice: 52900,
    wholesalePrice: 36000,
    wholesaleMinQty: 12,
    image: "/products/ninos/ninas-minnie-daisy.webp",
    backImage: "/products/ninos/ninas-minnie-daisy-back.webp",
    sizes: KIDS_SIZES,
    rating: 4.9,
    reviewCount: 28,
    stock: 66,
    store: STORE,
    description: "Camiseta infantil blanca y fucsia con estampado deportivo 'Minnie & Daisy' al frente y 'Girls Night In' en la espalda.",
  },
];

export type CartItem = {
  productId: string;
  qty: number;
  size?: string;
};

export const initialCart: CartItem[] = [
  { productId: "flames", qty: 1, size: "L" },
  { productId: "samurai", qty: 1, size: "M" },
];

export const sampleReview = {
  author: "Camila Rodríguez",
  rating: 5,
  date: "13 oct 2024",
  text: "Excelente calidad, superó mis expectativas. La entrega fue rápida y el producto llegó tal cual las fotos.",
};

export function getOnSaleProducts(limit?: number): Product[] {
  const sorted = [...products]
    .filter((p) => p.originalPrice && p.originalPrice > p.price)
    .sort((a, b) => {
      const discA = 1 - a.price / (a.originalPrice ?? a.price);
      const discB = 1 - b.price / (b.originalPrice ?? b.price);
      return discB - discA;
    });
  return typeof limit === "number" ? sorted.slice(0, limit) : sorted;
}

export function getBestSellers(limit?: number): Product[] {
  const sorted = [...products].sort((a, b) => b.reviewCount - a.reviewCount);
  return typeof limit === "number" ? sorted.slice(0, limit) : sorted;
}

export function ratingBreakdown() {
  const weights = [0.62, 0.24, 0.09, 0.03, 0.02];
  return [5, 4, 3, 2, 1].map((star, i) => ({ star, pct: Math.round(weights[i] * 100) }));
}

export function categorySlug(label: string): string {
  return categories.find((c) => c.label === label)?.id ?? label.toLowerCase();
}

// Formateador de moneda compartido (evita reimplementarlo en cada componente).
export const currency = new Intl.NumberFormat("es-CO", {
  style: "currency",
  currency: "COP",
  maximumFractionDigits: 0,
});

// Categorías cuyas fotos son de catálogo plano sobre fondo blanco (no de
// mockup/lifestyle), y por lo tanto se muestran con object-contain.
const BASIC_CATALOG_PHOTO_CATEGORIES = new Set(["Polos", "Buzos"]);

export function isBasicCatalogPhoto(category: string): boolean {
  return BASIC_CATALOG_PHOTO_CATEGORIES.has(category);
}

// Recomendaciones "también te puede gustar/interesar": prioriza productos de
// la misma categoría (y, si es posible, la misma audiencia) antes de
// completar con el resto del catálogo, para no recomendar prendas sin relación.
export function getRelatedProducts(
  product: Pick<Product, "id" | "category" | "audience">,
  limit = 4
): Product[] {
  const pool = products.filter((p) => p.id !== product.id);
  const sameCategoryAndAudience = pool.filter(
    (p) => p.category === product.category && (!product.audience || p.audience === product.audience)
  );
  const sameCategory = pool.filter((p) => p.category === product.category);
  const rest = pool.filter((p) => p.category !== product.category);

  const picked: Product[] = [];
  const seen = new Set<string>();
  for (const list of [sameCategoryAndAudience, sameCategory, rest]) {
    for (const p of list) {
      if (picked.length >= limit) break;
      if (seen.has(p.id)) continue;
      seen.add(p.id);
      picked.push(p);
    }
  }
  return picked;
}
