export type ConceptCategory = "Licores" | "Tecnología" | "Hogar y Cocina" | "Ropa Deportiva";

export type ConceptProduct = {
  id: string;
  name: string;
  category: ConceptCategory;
  price: number;
  image: string;
  rating: number;
  reviewCount: number;
};

export const conceptCategories: ConceptCategory[] = ["Licores", "Tecnología", "Hogar y Cocina", "Ropa Deportiva"];

export const conceptProducts: ConceptProduct[] = [
  // Licores
  {
    id: "concept-whisky",
    name: "Whisky Escocés 12 años",
    category: "Licores",
    price: 189900,
    image: "/concept/whisky.webp",
    rating: 4.8,
    reviewCount: 132,
  },
  {
    id: "concept-ron",
    name: "Ron Añejo Colombiano 8 años",
    category: "Licores",
    price: 79900,
    image: "/concept/rum.webp",
    rating: 4.6,
    reviewCount: 88,
  },
  {
    id: "concept-vino",
    name: "Vino Tinto Reserva",
    category: "Licores",
    price: 59900,
    image: "/concept/vino.webp",
    rating: 4.7,
    reviewCount: 64,
  },
  {
    id: "concept-aguardiente",
    name: "Aguardiente Tradicional",
    category: "Licores",
    price: 45900,
    image: "/concept/aguardiente.webp",
    rating: 4.5,
    reviewCount: 210,
  },
  {
    id: "concept-cerveza",
    name: "Cerveza Artesanal Pack x6",
    category: "Licores",
    price: 39900,
    image: "/concept/cerveza.webp",
    rating: 4.6,
    reviewCount: 97,
  },
  {
    id: "concept-champana",
    name: "Champaña Rosé Importada",
    category: "Licores",
    price: 129900,
    image: "/concept/champana.webp",
    rating: 4.9,
    reviewCount: 41,
  },
  {
    id: "concept-vodka",
    name: "Vodka Premium Importado",
    category: "Licores",
    price: 99900,
    image: "/concept/vodka.webp",
    rating: 4.7,
    reviewCount: 118,
  },
  {
    id: "concept-tequila",
    name: "Tequila Blue Agave",
    category: "Licores",
    price: 109900,
    image: "/concept/tequila.webp",
    rating: 4.6,
    reviewCount: 74,
  },
  {
    id: "concept-gin",
    name: "Gin Artesanal Small Batch",
    category: "Licores",
    price: 139900,
    image: "/concept/gin.webp",
    rating: 4.8,
    reviewCount: 62,
  },
  {
    id: "concept-cognac",
    name: "Cognac Reserva Especial",
    category: "Licores",
    price: 219900,
    image: "/concept/cognac.webp",
    rating: 4.7,
    reviewCount: 33,
  },
  // Tecnología
  {
    id: "concept-audifonos",
    name: "Audífonos Bluetooth Pro",
    category: "Tecnología",
    price: 149900,
    image: "/concept/audifonos.webp",
    rating: 4.7,
    reviewCount: 305,
  },
  {
    id: "concept-smartwatch",
    name: "Smartwatch Fitness Band",
    category: "Tecnología",
    price: 189900,
    image: "/concept/smartwatch.webp",
    rating: 4.5,
    reviewCount: 178,
  },
  {
    id: "concept-parlante",
    name: "Parlante Portátil Bluetooth",
    category: "Tecnología",
    price: 99900,
    image: "/concept/parlante.webp",
    rating: 4.6,
    reviewCount: 152,
  },
  {
    id: "concept-tv",
    name: "Televisor Smart 50\" 4K",
    category: "Tecnología",
    price: 1599900,
    image: "/concept/tv.webp",
    rating: 4.8,
    reviewCount: 76,
  },
  {
    id: "concept-laptop",
    name: "Portátil Ultradelgado 14\"",
    category: "Tecnología",
    price: 2199900,
    image: "/concept/laptop.webp",
    rating: 4.7,
    reviewCount: 59,
  },
  {
    id: "concept-consola",
    name: "Consola de Videojuegos",
    category: "Tecnología",
    price: 1299900,
    image: "/concept/consola.webp",
    rating: 4.9,
    reviewCount: 214,
  },
  {
    id: "concept-tablet",
    name: "Tablet 11\" Alta Resolución",
    category: "Tecnología",
    price: 1099900,
    image: "/concept/tablet.webp",
    rating: 4.6,
    reviewCount: 98,
  },
  {
    id: "concept-camara",
    name: "Cámara Mirrorless Profesional",
    category: "Tecnología",
    price: 2899900,
    image: "/concept/camara.webp",
    rating: 4.9,
    reviewCount: 45,
  },
  {
    id: "concept-dron",
    name: "Dron con Cámara 4K",
    category: "Tecnología",
    price: 1799900,
    image: "/concept/drone.webp",
    rating: 4.7,
    reviewCount: 67,
  },
  // Hogar y Cocina
  {
    id: "concept-ollas",
    name: "Juego de Ollas Antiadherentes x7",
    category: "Hogar y Cocina",
    price: 259900,
    image: "/concept/ollas.webp",
    rating: 4.7,
    reviewCount: 122,
  },
  {
    id: "concept-licuadora",
    name: "Licuadora de Alta Potencia",
    category: "Hogar y Cocina",
    price: 129900,
    image: "/concept/licuadora.webp",
    rating: 4.6,
    reviewCount: 143,
  },
  {
    id: "concept-nevera",
    name: "Nevera No Frost 300L",
    category: "Hogar y Cocina",
    price: 1899900,
    image: "/concept/nevera.webp",
    rating: 4.8,
    reviewCount: 68,
  },
  {
    id: "concept-lampara",
    name: "Lámpara de Mesa Minimalista",
    category: "Hogar y Cocina",
    price: 69900,
    image: "/concept/lampara.webp",
    rating: 4.5,
    reviewCount: 94,
  },
  {
    id: "concept-sofa",
    name: "Sofá Modular 3 Puestos",
    category: "Hogar y Cocina",
    price: 1499900,
    image: "/concept/sofa.webp",
    rating: 4.7,
    reviewCount: 51,
  },
  {
    id: "concept-cuchillos",
    name: "Set de Cuchillos Profesional",
    category: "Hogar y Cocina",
    price: 149900,
    image: "/concept/cuchillos.webp",
    rating: 4.8,
    reviewCount: 87,
  },
  {
    id: "concept-aspiradora",
    name: "Aspiradora Robot Inteligente",
    category: "Hogar y Cocina",
    price: 899900,
    image: "/concept/aspiradora.webp",
    rating: 4.6,
    reviewCount: 156,
  },
  {
    id: "concept-cafetera",
    name: "Cafetera Espresso Automática",
    category: "Hogar y Cocina",
    price: 349900,
    image: "/concept/cafetera.webp",
    rating: 4.7,
    reviewCount: 112,
  },
  // Ropa Deportiva
  {
    id: "concept-tenis",
    name: "Tenis para Correr",
    category: "Ropa Deportiva",
    price: 289900,
    image: "/concept/tenis.webp",
    rating: 4.8,
    reviewCount: 176,
  },
  {
    id: "concept-chaqueta-deportiva",
    name: "Chaqueta Deportiva Impermeable",
    category: "Ropa Deportiva",
    price: 159900,
    image: "/concept/chaqueta_dep.webp",
    rating: 4.6,
    reviewCount: 92,
  },
  {
    id: "concept-maleta-deportiva",
    name: "Maleta Deportiva de Viaje",
    category: "Ropa Deportiva",
    price: 119900,
    image: "/concept/maleta_dep.webp",
    rating: 4.7,
    reviewCount: 58,
  },
  {
    id: "concept-mancuernas",
    name: "Set de Mancuernas Ajustables",
    category: "Ropa Deportiva",
    price: 199900,
    image: "/concept/mancuernas.webp",
    rating: 4.7,
    reviewCount: 104,
  },
  {
    id: "concept-yogamat",
    name: "Tapete de Yoga Antideslizante",
    category: "Ropa Deportiva",
    price: 49900,
    image: "/concept/yogamat.webp",
    rating: 4.5,
    reviewCount: 130,
  },
  {
    id: "concept-balon",
    name: "Balón de Fútbol Profesional",
    category: "Ropa Deportiva",
    price: 129900,
    image: "/concept/balon.webp",
    rating: 4.7,
    reviewCount: 88,
  },
  {
    id: "concept-guantes",
    name: "Guantes de Boxeo Pro",
    category: "Ropa Deportiva",
    price: 99900,
    image: "/concept/guantes.webp",
    rating: 4.6,
    reviewCount: 54,
  },
  {
    id: "concept-termo",
    name: "Termo Deportivo de Acero",
    category: "Ropa Deportiva",
    price: 59900,
    image: "/concept/termo.webp",
    rating: 4.8,
    reviewCount: 142,
  },
];

export function getConceptProductsByCategory(category: ConceptCategory): ConceptProduct[] {
  return conceptProducts.filter((p) => p.category === category);
}
